### ISSUE TITLE
Surpass Anticheat

### ISSUE THREAD

**Issue by iGuest721** [xAranaktu/FC-24-Live-Editor#1]
Hey, I have a question/issue with Live Editor. With the free trial, can I continue playing with the Live Editor without the hours being recorded? I don't want to lose the hours. Basically, FC 24 for free

**Comment by Oliver-Turp** [comment]
> Hey, I have a question/issue with Live Editor. With the free trial, can I continue playing with the Live Editor without the hours being recorded? I don't want to lose the hours. Basically, FC 24 for free

No just buy the game
