### ISSUE TITLE
Error starting Launcher file

### ISSUE THREAD

**Issue by 3lyt** [xAranaktu/FC-24-Live-Editor#102]
Hello since the download I have had no problem but when wanting to play an error appeared in the attachment.

[Capture](https://github.com/xAranaktu/FC-24-Live-Editor/assets/160348059/f82c4730-8b97-454c-b2e5-4d5a2cac7161).

**Comment by xAranaktu** [comment]
Run live editor launcher -> go to settings -> change game location to directory where you have the game.

**Comment by 3lyt** [comment]
> Run live editor launcher -> go to settings -> change game location to directory where you have the game.

Sorry but I have the problem when I want to open LE so I can't open LE

**Comment by xAranaktu** [comment]
Try to delete `config.json` from `C:\FC 24 Live Editor`

**Comment by 3lyt** [comment]
The problem is not solved
![Capture](https://github.com/xAranaktu/FC-24-Live-Editor/assets/160348059/7ed707f8-8261-4092-8259-d890ae39eeaa)

**Comment by 3lyt** [comment]
Thanks for the help and I found the solution which is to put from C: to F:
