### ISSUE TITLE
Contract Status

### ISSUE THREAD

**Issue by biloonal** [xAranaktu/FC-24-Live-Editor#108]
Hello. First of all, I apologize for my bad English, I am writing with translate. I'm in the year 2047 in career mode, but I can't make contracts with players anymore. The duration of the contracts I renewed appears to be 2043 44 45 46 47, but the game continues to send contract messages and everyone except the top 18 leaves the team after the season. I wonder if there is any solution. Thanks in advance, good work.

**Comment by xAranaktu** [comment]
Nothing can be done with that. The game isn't able to store values higher than `2047` for contracts.
