### ISSUE TITLE
EA FC 24 Player Accelerate Type Edit in Live Editor

### ISSUE THREAD

**Issue by hamdi574215** [xAranaktu/FC-24-Live-Editor#111]
Hello all,

How do I change a player's acceleration type in player career or manager career? I want to make explosive but I can't make changes.

**Comment by xAranaktu** [comment]
Edit player attributes to match the acceleration type you want.
In [FC 24 Gameplay Deep Dive](https://www.ea.com/games/ea-sports-fc/pitch-notes/news/fc-24-gameplay-deepdive) you can find table with requirements for each AcceleRATE

**Comment by hamdi574215** [comment]
Hi
Even though I brought the player to the required physical characteristics, the acceleration type appears as "controlled" at the bottom of his name. How do I change this? I mostly want to make explosives. I edited its physical properties, but I cannot change the acceleration type.
