### ISSUE TITLE
Game forced shutdown issue after TU11 update

### ISSUE THREAD

**Issue by kunbiya** [xAranaktu/FC-24-Live-Editor#115]
I'm really using the live editor you produced. I'm registering the issue and thanking you like this.
The reason for registering the issue is as follows.

After the TU11 update, if you check Misc Features - Gameplay - perfect timed shot and play the game, the game will be forced to shut down.
I couldn't confirm the reason why the game was forced to end, so I registered it as an issue.
If this error is corrected, can it be applied to 1.1.6 or later versions?

**Comment by RiritoNinigaya** [comment]
**no, EA now fixed Anticheat and without Anticheat this game is just closing!!!**

**Comment by kunbiya** [comment]
After deleting the entire live editor folder on the C drive, erasing all configuration information, reinstalling and applying the perfect timed shot option, it works properly.
If there is a problem, we recommend that you delete it and reset it.
