### ISSUE TITLE
Yellow Game TU version

### ISSUE THREAD

**Issue by joaomacro** [xAranaktu/FC-24-Live-Editor#118]
My game is updated, my live editor is 24.1.1.5, but in LE is saying ''Your game version is newer...''
![imagem_2024-03-18_191925791](https://github.com/xAranaktu/FC-24-Live-Editor/assets/163932734/4b9291d3-9464-4c9c-ac73-3b6db3fd7c4c)

**Comment by joaomacro** [comment]
The game starts, works, but if i start a match, the game crash

**Comment by xAranaktu** [comment]
LE work fine. Your game crashes because you are using outdated mods which isn't related to live editor.
