### ISSUE TITLE
After the update, fc24 stopped opening with the live editor.

### ISSUE THREAD

**Issue by N0MEX1A** [xAranaktu/FC-24-Live-Editor#120]
My game, which was working properly, does not work from the application called EA after the update. When I run it from an application called epic games, it opens. But it never works with the live editor or the application called ea.

**Comment by Yippee420** [comment]
Unfortunately ou will have to wait for new LE version, usually it doesn't work after an update.

**Comment by xAranaktu** [comment]
Live Editor is working fine after the update. It's something on your end (probably outdated mods)

**Comment by N0MEX1A** [comment]
thank you for your response. it's working right now :)
