### ISSUE TITLE
Game always crashing with LE

### ISSUE THREAD

**Issue by SeyhArthur21** [xAranaktu/FC-24-Live-Editor#122]
As soon as I reach the main menu of the game, it gives an error and the game closes. At first I thought it was related to the mods, but the error continued after I deleted the mods.

When I enter the game normally, I do not encounter any errors.

[CrashReport_01042024163243123.json](https://github.com/xAranaktu/FC-24-Live-Editor/files/14823968/CrashReport_01042024163243123.json)
[log_01-04-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14823969/log_01-04-2024.txt)

**Comment by xAranaktu** [comment]
Turn off RivaTuner

**Comment by SeyhArthur21** [comment]
> Turn off RivaTuner

Thanks Budy
