### ISSUE TITLE
opening the editor for casual play like kickoff?

### ISSUE THREAD

**Issue by chiaraOwO** [xAranaktu/FC-24-Live-Editor#131]
Hey, 
is there a possibility to open up the editing features outside of carreer mode for kickoff and so on?
Obv. not for online usages or so but f.e. we like to draft our own teams when playin. So that means going into every single league and transfering the player from one club to another. Your tool seems perfect for it, especially with the lua scripts but afaik its not able to edit offline teams.

**Comment by xAranaktu** [comment]
Some features may not work, but overall it's possible to edit squad files with live editor.

1. In-game go to Customise->Profile->Load Squads->Pick the squad you want to use
2. Open Live Editor UI and change what you want to change. I don't know, for example change Messi attributes to 99.
3. Back to the game, Save Squads
4. Load Squads that you just saved
5. Go to kick off, make sure to disable "Live DB" or whatever it's called and you are done.

[Vide Example](https://streamable.com/vye7xl)

**Comment by chiaraOwO** [comment]
thanks man

**Comment by chiaraOwO** [comment]
thanks !

**Comment by chiaraOwO** [comment]
Is there anyway to do the savesquads/loadsquads with a lua script aswell?

**Comment by xAranaktu** [comment]
> Is there anyway to do the savesquads/loadsquads with a lua script aswell?

I don't think so.
