### ISSUE TITLE
FC 24 Live Editor Doesn't Launch

### ISSUE THREAD

**Issue by AwxkenBobb** [xAranaktu/FC-24-Live-Editor#135]
It worked before, but now it won't launch, no matter how many times I reinstall it. I think the problem arose when I tried to change the "mod data" location to the mod manager mods instead of keeping it as is - I've tried reinstalling it but that doesn't seem to work - if me redirecting the mod location in the program messed with it, is there a way to restore all default settings? Or would reinstalling it have fixed it and the problem is being caused by something else? Any insight would help a lot, thank you so much.
Oh - also when I double click the launcher, the message DOES come up for "do you want to allow this program to make changes to your device" I click YES and then it just doesn't open.

**Comment by xAranaktu** [comment]
You can restore default live editor setting by uninstalling live editor:
1. Close the game and live editor launcher
2. Run `LiveEditorClearRegistry.reg` (you can find this file in folder with live editor)
3. Delete folder with live editor
4. Delete `FC 24 Live Editor` folder from `C:/`

**Comment by AwxkenBobb** [comment]
Thank you so much! That worked! You should definitely put that in your troubleshooting Wiki!
