### ISSUE TITLE
Asset ID not saving

### ISSUE THREAD

**Issue by AwxkenBobb** [xAranaktu/FC-24-Live-Editor#136]
When I change a player's head ID and save it, it initially works in game, but if I restart the game it will not save and I have to restart the whole process every time.  It stopped saving after I launched the game without mods to play online but later when relaunched it through mod manager the updated head IDs did not save.

**Comment by xAranaktu** [comment]
You need to save the carer file, or squad file if you are editing outside of career mode. Anyway, it's not related to live editor.
