### ISSUE TITLE
Live Editor Launcher does not work "Error Can't find FC 24 in....." 

### ISSUE THREAD

**Issue by Zartanik** [xAranaktu/FC-24-Live-Editor#142]
Live editor just work perfectly fine the night before and today when open, i saw this message: 
![image](https://github.com/xAranaktu/FC-24-Live-Editor/assets/168538807/7dbda4ff-fc71-477e-8a30-e01f34f18b90)

Was opening log_launcher and noted this:
[17:24:24.118] [INFO] [Core::Init] Live Editor v24.1.1.5
[17:24:24.118] [INFO] [Core::Init] Game Install Dir: F:\Mods\Live Editor & CE\FC 24 LE v24.1.1.5
[17:24:24.118] [INFO] [Core::Init] Live Editor Dir: F:\SteamLibrary\steamapps\common\EA Sports FC 24\FC 24 LE v24.1.1.5
[17:24:24.118] [FATAL] [Core::Init] Can't find FC24.exe in:
F:\Mods\Live Editor & CE\FC 24 LE v24.1.1.5 

Seems like Live Editor somehow cannot detect the game folder. After the error message, it still show the usual warning but when i click ok, nothing happen, cannot see the console.
I have tried to delete LE, open again, also reinstall the game. still does not work. Can you please help me with this one?

**Comment by xAranaktu** [comment]
Reinstall live editor. 
To uninstall live editor:
1. Close the game and live editor launcher
2. Run `LiveEditorClearRegistry.reg` (you can find this file in folder with live editor)
3. Delete folder with live editor
4. Delete `FC 24 Live Editor` folder from `C:/`

**Comment by Zartanik** [comment]
I did exactly what you instruct, but this is how it response: 
![image](https://github.com/xAranaktu/FC-24-Live-Editor/assets/168538807/bfdf17f3-1f20-4f9e-a831-22255f4a1714)

**Comment by Zartanik** [comment]
i have attached the file. Much appreciated
[config.json](https://github.com/xAranaktu/FC-24-Live-Editor/files/15189609/config.json)

**Comment by xAranaktu** [comment]
Looks normal, so I don't know what makes your live editor launcher crash.
You can try to edit config.json manually and change `game_loc` to folder where your game is (I guess `F:\\SteamLibrary\\steamapps\\common\\EA Sports FC 24`)

**Comment by Zartanik** [comment]
adding the location manually has worked. My weekend is saved, thanks a lot.

**Comment by canbara2** [comment]
> Looks normal, so I don't know what makes your live editor launcher crash. You can try to edit config.json manually and change `game_loc` to folder where your game is (I guess `F:\\SteamLibrary\\steamapps\\common\\EA Sports FC 24`)

I have the same problem but I don't know what the above means? Please advise.

**Comment by fc24mod** [comment]
same problem as Jinglyboo here :(

**Comment by fc24mod** [comment]
@Zartanik @xAranaktu I didn't completly understand what the fix was... can you please elaborate a little bit more on what the change in location actually was? thanks

**Comment by Teneboy** [comment]
@Jinglyboo @fc24mod hi guys!
If the LiveEditor send u an error "cant find FC24.exe in:" — u need to open C:\FC 24 Live Editor and find a file "config.json"
Then u open it with Notepad++ and edit a sting:

"game_loc": "",

u must input there a direction to the EA FC 24 folder where the FC24.exe is

I give u my string as an example — "game_loc": "B:\\SteamLibrary\\steamapps\\common\\EA Sports FC 24",

**Comment by Jinglyboo** [comment]
Oh alright i replaced the text "gameloc" with the folder before

**Comment by Teneboy** [comment]
Only one important thing — use double slash everytime in the direction

**Comment by Jinglyboo** [comment]
In the direction? Where do i use the double slash here? "C:\Program Files (x86)\Steam\steamapps\common\EA Sports FC 24"

**Comment by Teneboy** [comment]
Use it everywhere, like in example:
![image](https://github.com/xAranaktu/FC-24-Live-Editor/assets/22795985/e8d37d75-0ffa-4672-a1e0-60c193b67ed7)

**Comment by Jinglyboo** [comment]
Thank you seems to be working fine its a bit buggy but idk

**Comment by fc24mod** [comment]
The weirdest thing is happening... I download LE but the config file is somehow missing from the original folder. I've tried taking the config.json file from a old download and put the gameloc manually as you explained, but I keep getting the same error.
Do you have any idea why that would happen ou what should I do to try to fix it?
Thanks a lot for the explanation given previously.

**Comment by fc24mod** [comment]
I've used the LiveEditorClearRegistry a couple of times, could that have any thing to do with whats is happening?

**Comment by Cantrafford** [comment]
Hi Everybody, I'm novice but someone knows the solution of my problem please ? When I run the game on the luncher, EA function but I receive this message 
What can I do ? 

Thanks for helping me ! :) best regrds 

![Capture d’écran 2024-07-24 095806](https://github.com/user-attachments/assets/b5ae2a6b-9499-488f-bf40-25901b027b77)

**Comment by Onuration** [comment]
I'm having trouble entering Live Editor, I press launcher but it doesn't open, the only thing I did was to do what user xAranaktu said "Run LiveEditorClearRegistry.reg (you can find this file in folder with live editor)", my live editor does not open.
