### ISSUE TITLE
Cheat Table Wont Open 

### ISSUE THREAD

**Issue by hexa666ram** [xAranaktu/FC-24-Live-Editor#147]
the cheat table just work fine before and now it wont open anymore, after launching the game with LE then i launch CT it doesn't show anything

**Comment by xAranaktu** [comment]
Run cheat engine first and from cheat engine open the cheat table.
You can also try to reinstall the cheat engine.

**Comment by joaozindelas** [comment]
![image_2024-08-03_173217454](https://github.com/user-attachments/assets/fee96a6e-8043-44e1-a7d9-ebcf8a7c8373)
 this is what my cheat table says after I open it idk what to do can anyone help me?
