### ISSUE TITLE
-dataPath FIFAModData showing up twice

### ISSUE THREAD

**Issue by j4ylesss** [xAranaktu/FC-24-Live-Editor#148]
Like the title says "-dataPath FIFAModData" shows up twice on start up, meaning game won't launch with mods. Tried removing it from Live Editor's Advanced Launch Options and verifying file integrity on Steam, but nothing works.

**Comment by xAranaktu** [comment]
https://github.com/xAranaktu/FC-24-Live-Editor/wiki/Getting-Started#launching-FC-24-live-editor-with-fifa-mod-manager-mods

**Comment by j4ylesss** [comment]
Yeah, the problem is that the argument shows up twice and my question is how do fix it. I followed the instructions but the argument is still there two times.

**Comment by j4ylesss** [comment]
Thanks for the fast reply, turns out I just can't read xD, thanks for the help man
