### ISSUE TITLE
Player head model spread sheet link was broken

### ISSUE THREAD

**Issue by pinij** [xAranaktu/FC-24-Live-Editor#15]
Player head model spread sheet [link](https://bit.ly/FC-24-IDs)  in [wiki page](https://github.com/xAranaktu/FC-24-Live-Editor/wiki/Editing-Player) was broken.  Please update new link thank you.

**Comment by xAranaktu** [comment]
Fixed. Correct link -> [here](https://bit.ly/EAFC-24-IDS)

**Comment by pinij** [comment]
Thank you
