### ISSUE TITLE
Glitched out after new update

### ISSUE THREAD

**Issue by primecai** [xAranaktu/FC-24-Live-Editor#162]
It could be just me, but seems like the new update yesterday makes v1.1.5 glitch out while loading the teams/players, etc.

**Comment by vuminhman** [comment]
Same thing happened for me.

**Comment by primecai** [comment]
It appears 1.1.5 works if I force the game to not connect to the EA server (cancel connection during the loading screen).

**Comment by nelstarlol** [comment]
> It appears 1.1.5 works if I force the game to not connect to the EA server (cancel connection during the loading screen).

Mine doesn't even get that far now. It freezes immediately when the game opens for me..
Any advice?

**Comment by xAranaktu** [comment]
> It could be just me, but seems like the new update yesterday makes v1.1.5 glitch out while loading the teams/players, etc.

Fixed in [FC 24 Live Editor v24.1.1.6](https://www.patreon.com/posts/105763730)
