### ISSUE TITLE
FC 24 freezing after the start screen

### ISSUE THREAD

**Issue by wise101127** [xAranaktu/FC-24-Live-Editor#165]
I updated FC24 to the latest version. I open uisng Live Editor>>Run Game. It will open fine all the way to the start screen. after pressing start it will go to the loading screen then freeze. It works fine if I start from the EA app but any mods on the i have on fifamodmanager don't apply. So I'm not 100% sure if it is due to LE or mod manager but it only freezes if a launch through LE.

**Comment by ImAlvaroToscano** [comment]
Same issue :(

**Comment by xAranaktu** [comment]
Issue with your mods. Not related to live editor.
