### ISSUE TITLE
Crashing after opening Live Editor in save. (Euro Update)

### ISSUE THREAD

**Issue by wulfify** [xAranaktu/FC-24-Live-Editor#166]
Live editor will open on loading into menu and can close fine. Once in a save and open LE crashes. Tested multiple times with 100% replication rate. Verified FC24 files and tested on new LE files.

FC24 Version: Euro Update/TU15?
LE Version: 24.1.1.5

Logs:
[CrashReport_06062024215914997.json](https://github.com/user-attachments/files/15696627/CrashReport_06062024215914997.json)
[log_06-06-2024.txt](https://github.com/user-attachments/files/15696642/log_06-06-2024.txt)
[log_launcher_06-06-2024.txt](https://github.com/user-attachments/files/15696656/log_launcher_06-06-2024.txt)

**Comment by SirDnoob** [comment]
Yeah, I'm having the same problem. Still don't know why it doesn't work.

**Comment by kaido9097** [comment]
any fix yut?

**Comment by kaido9097** [comment]
it also crashes when i try to loan a player through the live editor
on a new save

**Comment by xAranaktu** [comment]
> Once in a save and open LE crashes

Fixed in [FC 24 Live Editor v24.1.1.6](https://www.patreon.com/posts/105763730)
