### ISSUE TITLE
Game crash when opening Live Editor in Career Mode

### ISSUE THREAD

**Issue by ini-Ojan** [xAranaktu/FC-24-Live-Editor#167]
Everything works fine in the main menu of FC 24. I can access the Live Editor menu and adjust to my liking without a problem. When I go to my Career Mode though, if I try to open the 'Player' submenu of the Live Editor menu my game crashes. Any help?
I'm trying to adjust the potential of a few of my players in my manager career mode.

**Comment by ini-Ojan** [comment]
If you want log files 
[CrashReport_07062024160253605.json](https://github.com/user-attachments/files/15731171/CrashReport_07062024160253605.json)
[log_07-06-2024.txt](https://github.com/user-attachments/files/15731183/log_07-06-2024.txt)
[log_launcher_07-06-2024.txt](https://github.com/user-attachments/files/15731189/log_launcher_07-06-2024.txt)

**Comment by primecai** [comment]
Are you loading with ```
-datapath FIFAModData
``` advance option? Mine works if I don't use mod but crashes in career mode if I do use mod.

**Comment by CrifferS** [comment]
please let me know when you solve the problem

**Comment by xAranaktu** [comment]
> if I try to open the 'Player' submenu of the Live Editor menu my game crashes.

Fixed in [FC 24 Live Editor v24.1.1.6](https://www.patreon.com/posts/105763730)

**Comment by youssefyehia198** [comment]
also, fc 24 live editor v24.1.1.6 is crashing
