### ISSUE TITLE
TU15 for people whit no money when will it come out?

### ISSUE THREAD

**Issue by sennTHEFIFA** [xAranaktu/FC-24-Live-Editor#175]
i can't use it whitout TU15 i am poor asf?

**Comment by xAranaktu** [comment]
[Release Schedule For FC 24 Projects](https://docs.google.com/spreadsheets/d/1QQzz37XEH1VCN4pJ0G2dwCfg4jLbYehLcVP-h3qIjr8/edit#gid=1821816083)
