### ISSUE TITLE
crashing game

### ISSUE THREAD

**Issue by Gorlyy** [xAranaktu/FC-24-Live-Editor#176]
the time editor opens game crashing

**Comment by enskksl** [comment]
YES I AM EXPERIENCED THIS PROBLEM TOO

**Comment by yuikotegawa123** [comment]
it is not working with TU15.1

**Comment by Falafio** [comment]
Whenever I try to launch the game it instantly crashes after a few seconds in the select the profile screen

**Comment by Mlacko977** [comment]
Live editor 1.1.6 not working or 1.1.5

**Comment by Comisaru37** [comment]
> Live editor 1.1.6 not working or 1.1.5

1.1.6 not working, it was working after the first euro update but then EA released another update today that apparently did nothing much to the game. after that update 1.1.6 is not working anymore

**Comment by Mlacko977** [comment]
Then he must too make updatee

**Comment by magasaurus** [comment]
hope Aranaktu fix this soon <3 Goodluck my friend!

**Comment by Comisaru37** [comment]
@xAranaktu trusting you can work your magic on this one 👍

**Comment by MangoJPG** [comment]
Have this problem as well. It is the Live Editor with the new version, game is running fine without it. But crashes somewhere between 1 - 20 seconds of the game opening with Live Editor open unfortunately

**Comment by yaelhrmns** [comment]
So we just have to wait for an unpdate ?

**Comment by xAranaktu** [comment]
Today (10th June 2024) EA has released new game update (TU15.1).
This update has broken the Live Editor. 
Live Editor doesn't work currently, wait for fix.
Don't update your game.
No, you can't use cheat table without live editor.

No ETA. I don't know how long it will that to find a solution. Maybe 1 day, maybe it will never happen.

**Comment by Comisaru37** [comment]
anyone know how to reverse the last update?

**Comment by TZeng20** [comment]
How do we stop update through steam? Steam always opens when we launch the game through live editor

**Comment by xAranaktu** [comment]
Problem with game crashes after updating the game to TU15.1 has been solved in [FC 24 Live Editor v24.1.1.7](https://www.patreon.com/posts/105987056)

**Comment by Comisaru37** [comment]
> Problem with game crashes after updating the game to TU15.1 has been solved in [FC 24 Live Editor v24.1.1.7](https://www.patreon.com/posts/105987056)

legend
