### ISSUE TITLE
EAFC 24, crash at launching by LE

### ISSUE THREAD

**Issue by yaelhrmns** [xAranaktu/FC-24-Live-Editor#177]
Hello, (sorry for my bad english)

My game is crashing when i launch the game by LE but when I start it by EA without LE, it works very well

I tried to reinstall LE and repair FC24 but ii still doesn't work.
Please, can you help me for that.

Thank you

**Comment by Alibarqi27** [comment]
> Hello, (sorry for my bad english)
> 
> My game is crashing when i launch the game by LE but when I start it by EA without LE, it works very well
> 
> I tried to reinstall LE and repair FC24 but ii still doesn't work. Please, can you help me for that.
> 
> Thank you

it's happen after update minor update in fc24

**Comment by icefps22** [comment]
Hello, I have the same problem, the game simply crashes when opening with the live editor for 1 to 20 seconds
