### ISSUE TITLE
FC 24 stuck in the start screen

### ISSUE THREAD

**Issue by YukkiHen** [xAranaktu/FC-24-Live-Editor#181]
When i start FC24 using LE it get stucked and freezed in the the start screen, i do not use any mods and i use the most up to date version of LE.
![Captura de tela 2024-06-11 153658](https://github.com/xAranaktu/FC-24-Live-Editor/assets/172400107/9b8d7821-1b2d-4fc4-8595-f1eca31f8c73)
![Captura de tela 2024-06-11 153744](https://github.com/xAranaktu/FC-24-Live-Editor/assets/172400107/9cfeeb7d-1c92-43fc-a185-53bc3ad0cf4b)

**Comment by xAranaktu** [comment]
It can happen from time to time. Just close the game and try again.
If this occur every single time then, sorry but it's issue with your mods, not live editor.

**Comment by LarsvanA** [comment]
> It can happen from time to time. Just close the game and try again. If this occur every single time then, sorry but it's issue with your mods, not live editor.

but he just said he didnt even use mods so how can it be the issue with the mods if he aint using them?

mine crashes the whole time and im not using mods

**Comment by xAranaktu** [comment]
> but he just said he didnt even use mods so how can it be the issue with the mods if he aint using them?

I'm doing this for a few years already and I know that what people say isn't necessarily a truth. Many people isn't aware that even if you don't run mod manager it doesn't mean that the game run without mods.
I hear that everyday, and then I see this:
![](https://camo.githubusercontent.com/409e87ea56946ed16a9faa296d39640112bb25052e2fc55c8d947e8abfc3c912/68747470733a2f2f692e696d6775722e636f6d2f6d6947625341702e706e67)

So, if you see that your game starts with `-dataPath FIFAModData` then no matter what you think or what you say it means you are using mods. Get rid of that launch option and it will fix your problems.
