### ISSUE TITLE
fc24 live editor crashdump

### ISSUE THREAD

**Issue by hemkn2** [xAranaktu/FC-24-Live-Editor#182]
Attempting to edit with the live editor in fc24 maneger career forces the game to close 
![20240611232710_1](https://github.com/xAranaktu/FC-24-Live-Editor/assets/172411450/9315ba1c-851b-4d9d-b946-69ec89591bf7)

**Comment by xAranaktu** [comment]
Only [FC 24 Live Editor v24.1.1.7](https://www.patreon.com/posts/fc-24-live-v24-1-105987056) work with TU 15.1
