### ISSUE TITLE
How can i download v24.1.1.7 live editor 

### ISSUE THREAD

**Issue by Gamerusielfifa** [xAranaktu/FC-24-Live-Editor#183]
I really cant find any links to downloading v24.1.1.7 version of live editor and i need it because v24.1.1.5 does not work on newest ea fc 24 version

**Comment by Gamerusielfifa** [comment]
w sumie to możesz odpowiedzieć mi po polsku

**Comment by xAranaktu** [comment]
[FC 24 Live Editor v24.1.1.7](https://www.patreon.com/posts/fc-24-live-v24-1-105987056)
