### ISSUE TITLE
24.1.1.5

### ISSUE THREAD

**Issue by thejohhnn** [xAranaktu/FC-24-Live-Editor#184]
This version of live editor crashes every single possible time, even without mods. Between 5-15seconds after launch.. crash.. and no crash report from live editor/mod manager... TU 15.1

**Comment by Gamerusielfifa** [comment]
i have the same problem and i dont know how to update LE

**Comment by thejohhnn** [comment]
Well the newer versions are paid now.. they will be free in 7 days.. you can find it here: https://bit.ly/FC-24-Release-Schedule

**Comment by xAranaktu** [comment]
Only [FC 24 Live Editor v24.1.1.7](https://www.patreon.com/posts/fc-24-live-v24-1-105987056) work with TU 15.1

**Comment by thejohhnn** [comment]
Okay, thanks for info...
