### ISSUE TITLE
new live editor version will be free?

### ISSUE THREAD

**Issue by ryhme370** [xAranaktu/FC-24-Live-Editor#189]
new live editor version will be free?

**Comment by xAranaktu** [comment]
Yes. [Release Schedule For FC 24 Projects](https://docs.google.com/spreadsheets/d/1QQzz37XEH1VCN4pJ0G2dwCfg4jLbYehLcVP-h3qIjr8/edit#gid=1821816083)

**Comment by ryhme370** [comment]
thanks all the best
