### ISSUE TITLE
Request for FIFA 23 Live Editor

### ISSUE THREAD

**Issue by phurkanofc** [xAranaktu/FC-24-Live-Editor#19]
I'm sorry to disturbing you about FIFA 23 but ther's a problem about "Formation" tab. I tried with 2 different graphic cards and I even factory resetted my system and tried all of the solutions I saw on the internet but the problem didn't solve.

Everytime I try to open Formation tab, this message comes up and game just closing after clicking the "OK".

Directx function "GetDeviceRemovedReason" failed with DXGI_ERROR_INVALID_CALL ("The application provided invalid parameter data; this must be debugged and fixed before the application is released."). GPU: "NVIDIA GeForce RTX 3070" Driver: 54584

**Comment by xAranaktu** [comment]
Maybe one of the players has invalid miniface. If it happens for any team then I don't know. Disable loading images in LE settings. I'll not make any updates for FIFA 23 or older tools.
