### ISSUE TITLE
game crash when launch

### ISSUE THREAD

**Issue by creesbby** [xAranaktu/FC-24-Live-Editor#195]
pleaseee broo help me why always crash whn i launch it

**Comment by JeSuisDany** [comment]
Same for me , it doesn't even say anything like "error" or something it just sends me back to ea app and EAFC24 works perfectly fine when playing without the mods

**Comment by creesbby** [comment]
yes broo samee, pls help us we really want to play with the editor

**Comment by xAranaktu** [comment]
> Same for me , it doesn't even say anything like "error" or something it just sends me back to ea app and EAFC24 works perfectly fine when playing without the mods

Congratulations, you just discovered that the issue is with your mods, not live editor. I don't know why you open ticket here. Contact with mod authors.

**Comment by creesbby** [comment]
i think the mods he mean is live editor bro, pls help me i really wanna play with the tools

**Comment by JeSuisDany** [comment]
Yeh that's what I meant , probably you need to wait till 18.06 to get the new version of live editor maybe it will work. Because it is so weird last night it was working and now it isn't. We might need just to wait , idk
