### ISSUE TITLE
Live Editor Does not work

### ISSUE THREAD

**Issue by mazeblitz** [xAranaktu/FC-24-Live-Editor#197]
recently Live Editor didn't work for me (It would crash after editing a player)  I thought It was because of the out dated version of the live editor but after downloading the newer version (v24.1.1.6) it works even worse, now I can't even do anything, the game automatically crashes even before getting into the menu, I would highly appreciate if I would get an answer to fix this problem

**Comment by xAranaktu** [comment]
Only LE  v24.1.1.7 work with TU15.1
