### ISSUE TITLE
FC 24 Live Editor v24.1.1.7 Crashing on launch with or without mods

### ISSUE THREAD

**Issue by JPMEXICAN12** [xAranaktu/FC-24-Live-Editor#205]
FC 24 Live Editor v24.1.1.7 Crashing on launch with or without mods on starting screen, rigth when it tells to cancel online play it crashes, even without the mods

**Comment by xAranaktu** [comment]
send log files

**Comment by JPMEXICAN12** [comment]
> send log files

Where are those files located?

**Comment by xAranaktu** [comment]
In `Logs` folder in the same directory where your live editor is.

**Comment by JPMEXICAN12** [comment]
[CrashReport_17062024010655140.json](https://github.com/user-attachments/files/15865299/CrashReport_17062024010655140.json)
[log_17-06-2024.txt](https://github.com/user-attachments/files/15865300/log_17-06-2024.txt)
[log_launcher_17-06-2024.txt](https://github.com/user-attachments/files/15865301/log_launcher_17-06-2024.txt)

**Comment by xAranaktu** [comment]
Issue with your mods. Every single game run is with `-dataPath FIFAModData`. Remove it and you should be good.

**Comment by JPMEXICAN12** [comment]
So will it no longer work with mods?

**Comment by JPMEXICAN12** [comment]
> Issue with your mods. Every single game run is with `-dataPath FIFAModData`. Remove it and you should be good.

So will it no longer work with mods?
