### ISSUE TITLE
How do I remove -dataPath FIFAModData

### ISSUE THREAD

**Issue by IDunnoig** [xAranaktu/FC-24-Live-Editor#209]
I have no idea what I did when setting everything up but I used to have mod manager, from what I read I need to remove -dataPath FIFAModData, though I have no idea how, in the ea app there is no "properties" so I have no idea where else I could have put -dataPath FIFAModData, would it be possible to tell me the location so I can remove it.

**Comment by CJGISVERYCOOL** [comment]
go to your fc 24 on steam then on general should have -data path fifa mod data which then you just get rid of

**Comment by IDunnoig** [comment]
oh yeah thanks
