### ISSUE TITLE
Player Cloning returns nil attributes.

### ISSUE THREAD

**Issue by zzlyz** [xAranaktu/FC-24-Live-Editor#225]
Hey im using the latest version of eafc of 1.0.89.16541 and LE v24.1.1.7
i started a career mode as grimsby town and wanted to edit a player called danny rose and give him messi's attributes
however this came up?

![image](https://github.com/xAranaktu/FC-24-Live-Editor/assets/84344494/c21b3241-ebdd-45bb-b876-4ed4f12d4d81)

is there something wrong with my game? or the live editor itself

**Comment by xAranaktu** [comment]
CT is no longer able to retrieve data about cards from futbin because they updated their website. Won't be fixed
