### ISSUE TITLE
Live editor Error

### ISSUE THREAD

**Issue by littlel3ni** [xAranaktu/FC-24-Live-Editor#229]
Good morning, I'm using Google Translate so I apologize if the message has any errors.

I am unable to use the Live editor, I will leave the error message as an attachment. I have EA offline, I tried to install an older driver, I ran it in administrator mode and always the same error. The game and live editor are in compatible versions.
![Captura de Tela (61)](https://github.com/xAranaktu/FC-24-Live-Editor/assets/174258100/8804db5a-4093-450b-8c71-6d39bc1143bb)

**Comment by xAranaktu** [comment]
Probably you are using something from [Blacklist](https://github.com/xAranaktu/FC-24-Live-Editor/wiki/Blacklist)

**Comment by littlel3ni** [comment]
I was using MSI Afterburner, thanks!
