### ISSUE TITLE
FC24 stuck in start up screen when using LE

### ISSUE THREAD

**Issue by davrocks777** [xAranaktu/FC-24-Live-Editor#232]
Hi there,

I accidentally updated my FC24 game to the latest version and now it does not work with the Live (LE). 

I am able to play the game without the LE but when I try with the LE, it just stays the screen shown below

Screenshot of where game stays stuck
![image](https://github.com/xAranaktu/FC-24-Live-Editor/assets/174321541/ec75f299-3161-4686-85be-1d0a33ce685d)

These are my logs: 
[log_launcher_01-07-2024.txt](https://github.com/user-attachments/files/16050791/log_launcher_01-07-2024.txt)

**Comment by xAranaktu** [comment]
It doesn't work because you are playing with outdated mods. Run the game without them and it will work. Nothing wrong with live editor here.

**Comment by davrocks777** [comment]
Thank you so much! It worked
