### ISSUE TITLE
Crash after Windows Button press

### ISSUE THREAD

**Issue by Ganjalf19** [xAranaktu/FC-24-Live-Editor#240]
hello everyone 
Once the game is started, as soon as I press the Windows key I receive this type of error, with crash consequences. 

Possible solutions? 

Many thanks in advance !

![Senza titolo](https://github.com/xAranaktu/FC-24-Live-Editor/assets/174886223/6e3a9aea-bc10-4697-bc0d-df57e00a58de)

**Comment by xAranaktu** [comment]
send log files

**Comment by Ganjalf19** [comment]
Where can i found it?

**Comment by Ganjalf19** [comment]
Here are attachments! 
Thanks in advance!!

[log_06-07-2024.txt](https://github.com/user-attachments/files/16120135/log_06-07-2024.txt)
[log_launcher_06-07-2024.txt](https://github.com/user-attachments/files/16120136/log_launcher_06-07-2024.txt)

**Comment by xAranaktu** [comment]
```
[15:57:17.866] [28500] [ERROR] DX12 Error at d3d12hook::ResizeBuffers - hr = 0x887A0001
```

Same as in #236 
There is no known fix, sorry.

**Comment by Ganjalf19** [comment]
sooo bad, I'll try reinstalling the game

thank you so much!
