### ISSUE TITLE
UI and player photos looks like weird and cursed. 

### ISSUE THREAD

**Issue by shiroyai** [xAranaktu/FC-24-Live-Editor#246]
- Using last version.
- Using last FC24 version.
- Not using with FIFA Mod Manager.

![image](https://github.com/user-attachments/assets/1bae9098-bd6d-4872-b6bd-d15d62c00f87)
Colors are glitched and some buttons has a cross line. 
I didn't see any options about that. I don't know, how to fix this problem?

**Comment by xAranaktu** [comment]
It's because you have AMD GPU. There is no known fix (other than switching to NVIDIA GPU)
