### ISSUE TITLE
Sign in error?

### ISSUE THREAD

**Issue by haktan6161** [xAranaktu/FC-24-Live-Editor#251]
![image](https://github.com/user-attachments/assets/87e27d33-2925-44a4-bdaa-e9c9f61032cd) 
It won't open even though I entered the required information
Here are a few more images that might help understand what the problem is:
![image](https://github.com/user-attachments/assets/cf586565-645b-43e3-a37a-a3a2c364598c)
![image](https://github.com/user-attachments/assets/845c25aa-6e0b-4b0b-b8e3-7641b21a5ef1)
![image](https://github.com/user-attachments/assets/305ee7d4-3c6b-4e7c-bff7-40896413b14f)

**Comment by YukkiHen** [comment]
same problem

**Comment by haktan6161** [comment]
Uploading unknown_2024.07.23-14.50.mp4…

**Comment by haktan6161** [comment]
https://github.com/user-attachments/assets/163908e4-daa8-469e-b286-48266f8a41c6

**Comment by Michal991-1** [comment]
Same problem

**Comment by Trystandsm** [comment]
Yep same here I’m glad it’s not only for me I hope there will be a solution pretty soon

**Comment by xAranaktu** [comment]
First of all run the game without any mods or tools, connect to EA servers and reach game main menu. After a few seconds close the game. This should make your game copy activated for a while.

Then change injection delay in live editor settings. 
![](https://i.imgur.com/OQIXgP3.png)
There is no universal value, so you need to find a one that will work for you by yourself. It all depends on how fast your PC is able to boot the game. I had to increase it from 100ms to 3000-4000ms and run the game directly from EA App to make it work.
Run live editor launcher and leave it working in the background (don't press run game button in it).
Then open EA App/Steam/Epic and run your game from there
![](https://i.imgur.com/uhPUvoL.png)

If you still get the activation popup with 4000 then increase the value to 5000-6000 or more.

**Comment by Michal991-1** [comment]
thanks for your help, it already worked

**Comment by aerooooooo** [comment]
> First of all run the game without any mods or tools, connect to EA servers and reach game main menu. After a few seconds close the game. This should make your game copy activated for a while.
> 
> Then change injection delay in live editor settings. ![](https://camo.githubusercontent.com/8850f089fd6c586d4b6f233fb5b823eaad0d77d3410d8f724b52be3d3645f1b6/68747470733a2f2f692e696d6775722e636f6d2f4f5149586750332e706e67) There is no universal value, so you need to find a one that will work for you by yourself. It all depends on how fast your PC is able to boot the game. I had to increase it from 100ms to 3000-4000ms and run the game directly from EA App to make it work. Run live editor launcher and leave it working in the background (don't press run game button in it). Then open EA App/Steam/Epic and run your game from there ![](https://camo.githubusercontent.com/2e21e72a86edf03a590d5de95d499ef917bd914b2a6b885acb581a77c12a3030/68747470733a2f2f692e696d6775722e636f6d2f75685055766f4c2e706e67)
> 
> If you still get the activation popup with 4000 then increase the value to 5000-6000 or more.

is there a simpler solution or is this the only one?

**Comment by haktan6161** [comment]
Thanks thats worked.

**Comment by aerooooooo** [comment]
> > is there a simpler solution or is this the only one?
> 
> There isn't any other known solution.

Will there be an update for LE soon with a fix or?

**Comment by Ganjalf19** [comment]
> First of all run the game without any mods or tools, connect to EA servers and reach game main menu. After a few seconds close the game. This should make your game copy activated for a while.
> 
> Then change injection delay in live editor settings. ![](https://camo.githubusercontent.com/8850f089fd6c586d4b6f233fb5b823eaad0d77d3410d8f724b52be3d3645f1b6/68747470733a2f2f692e696d6775722e636f6d2f4f5149586750332e706e67) There is no universal value, so you need to find a one that will work for you by yourself. It all depends on how fast your PC is able to boot the game. I had to increase it from 100ms to 3000-4000ms and run the game directly from EA App to make it work. Run live editor launcher and leave it working in the background (don't press run game button in it). Then open EA App/Steam/Epic and run your game from there ![](https://camo.githubusercontent.com/2e21e72a86edf03a590d5de95d499ef917bd914b2a6b885acb581a77c12a3030/68747470733a2f2f692e696d6775722e636f6d2f75685055766f4c2e706e67)
> 
> If you still get the activation popup with 4000 then increase the value to 5000-6000 or more.


I followed the procedure, once I started the game via the EA platform nothing happens.
 I wait a few seconds and the EA screen reappears, without the game trying to start. 
Do I have to change the Delay or something?

**Comment by xAranaktu** [comment]
> Will there be an update for LE soon with a fix or?

I don't think so. It's not issue with Live Editor. It's related to Denuvo and I don't plan to crack this game, so nothing else can be done.

**Comment by ErickTriton** [comment]
did you attempt it with mods active aswell?

**Comment by SirBeta2710** [comment]
Hi, sorry but struggling here. I started at 4000m/s and went right up in increments of 100 to try and fix, reached 7k and still no good, are my increments too large? Would you possibly be able to do a video to cover this I would be so grateful!!
Many thanks
