### ISSUE TITLE
Not working after todays update.

### ISSUE THREAD

**Issue by schoenmatheus** [xAranaktu/FC-24-Live-Editor#253]
Shows a old origin login after the update. 

Below follows the log generated from it.

thanks

[log_23-07-2024.txt](https://github.com/user-attachments/files/16354443/log_23-07-2024.txt)
[log_launcher_23-07-2024.txt](https://github.com/user-attachments/files/16354444/log_launcher_23-07-2024.txt)

**Comment by Comisaru37** [comment]
same for me, pissed off as it done the update without me noticing otherwise i don't usually update it... i get the old log in screen
![Screenshot 2024-07-23 233427](https://github.com/user-attachments/assets/d0a6acb7-00dd-4508-8ed5-b969c361ae04)

**Comment by chatgpter** [comment]
dont press 'run game' button on editor,let editor work background,open fc24 in steam.

**Comment by chtourou-youssef** [comment]
can you more explain the solution please ?

**Comment by chatgpter** [comment]
> can you more explain the solution please ?

First of all run the game without any mods or tools, connect to EA servers and reach game main menu. After a few seconds close the game. This should make your game copy activated for a while.

Then change injection delay in live editor settings. 
![68747470733a2f2f692e696d6775722e636f6d2f4f5149586750332e706e67](https://github.com/user-attachments/assets/89c15ae7-de7a-4828-b87d-fbd55c53c509)
There is no universal value, so you need to find a one that will work for you by yourself. It all depends on how fast your PC is able to boot the game. I had to increase it from 100ms to 3000-4000ms and run the game directly from EA App to make it work.
Run live editor launcher and leave it working in the background (don't press run game button in it).
Then open EA App/Steam/Epic and run your game from there
![68747470733a2f2f692e696d6775722e636f6d2f75685055766f4c2e706e67](https://github.com/user-attachments/assets/16fa2f87-b96e-4a1e-a9c2-8762ae22fbc3)
 i just fixed same problem by following this way,i hope yours will too.
quote from:https://github.com/xAranaktu/FC-24-Live-Editor/issues/251

**Comment by Comisaru37** [comment]
i launch the game from editor tool so i can apply some mods as well, and i still get the same error
![Uploading Screenshot 2024-07-23 233427.png…]()

**Comment by chatgpter** [comment]
> i launch the game from editor tool so i can apply some mods as well, and i still get the same error ![Screenshot 2024-07-23 233427](https://private-user-images.githubusercontent.com/172287403/351628520-97924e37-3ee3-4a78-a30d-56d276c70997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDg4OTUsIm5iZiI6MTcyMTgwODU5NSwicGF0aCI6Ii8xNzIyODc0MDMvMzUxNjI4NTIwLTk3OTI0ZTM3LTNlZTMtNGE3OC1hMzBkLTU2ZDI3NmM3MDk5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTQxZmMyMmQxZGU0ZmRmYmQ1ZGYyNzgxYjhlMzFlMDliNTk2MjIwYjA2YTEwZGIzNmVjOGQyZTZjYTYwYjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-lh1aq4iecdptu6A2MwuwovMm-6V5pZ4kyNmrfD9HyA)

i think you can follow which solution i mentioned above,coz i solved same problem with yours yesterday.better try to change DLL injection to 4000ms or more,there is no universal value for everyone.

**Comment by chatgpter** [comment]
> i launch the game from editor tool so i can apply some mods as well, and i still get the same error ![Screenshot 2024-07-23 233427](https://private-user-images.githubusercontent.com/172287403/351628520-97924e37-3ee3-4a78-a30d-56d276c70997.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MDg4OTUsIm5iZiI6MTcyMTgwODU5NSwicGF0aCI6Ii8xNzIyODc0MDMvMzUxNjI4NTIwLTk3OTI0ZTM3LTNlZTMtNGE3OC1hMzBkLTU2ZDI3NmM3MDk5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcyNFQwODA5NTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNTQxZmMyMmQxZGU0ZmRmYmQ1ZGYyNzgxYjhlMzFlMDliNTk2MjIwYjA2YTEwZGIzNmVjOGQyZTZjYTYwYjBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.-lh1aq4iecdptu6A2MwuwovMm-6V5pZ4kyNmrfD9HyA)

after change DLL injection,try launch the game via steam/epic,do not press "run game" botton on live editor.

**Comment by xAranaktu** [comment]
Read [Workaround for the Game Activation Window](https://www.patreon.com/posts/workaround-for-108717509)
As there is no other solution for that issue you have basically two options:
1. Keep trying until you will find a delay that will work for you
or
2. Give up and play without live editor.
