### ISSUE TITLE
Live Editor Opening Problem

### ISSUE THREAD

**Issue by Tolga0077** [xAranaktu/FC-24-Live-Editor#255]
I get this error when opening the game. Although sometimes it doesn't give an error, this time I encounter this problem.
![Ekran görüntüsü 2024-07-24 141430](https://github.com/user-attachments/assets/3a738c4f-7e55-46cf-bfe7-3ce2c966a946)
![image](https://github.com/user-attachments/assets/e53b7bc7-0061-4afc-9300-20bcb6b0d0e1)
Even if I enter my information, the game does not open.

**Comment by xAranaktu** [comment]
Read [Workaround for the Game Activation Window](https://www.patreon.com/posts/workaround-for-108717509)
