### ISSUE TITLE
FC24 start but like a Background task

### ISSUE THREAD

**Issue by TheBGA** [xAranaktu/FC-24-Live-Editor#265]
I got the new LE version and change some DLL Injector and the game start, Steam says game is launch and i see it in my Task Manager but i dont see the window game...

**Comment by SirBeta2710** [comment]
Having the same issue as this, have the latest version (paid one), any ideas please?

**Comment by xAranaktu** [comment]
Only Live Editor v24.1.1.9 work with TU18.2

**Comment by SirBeta2710** [comment]
> Only Live Editor v24.1.1.9 work with TU18.2

Is that released yet?

**Comment by SirBeta2710** [comment]
Thank you for your help. Greatly appreciated!
