### ISSUE TITLE
Fc 24 live editor launch issue

### ISSUE THREAD

**Issue by CharlesLeclrec123** [xAranaktu/FC-24-Live-Editor#266]
After the 18.2 update,I cannot launch the game with LE,I tried the solution of running le at background and open the game with ea app,but still doesnt work.Is there any other method to launch the game with le?

**Comment by TheoJumper** [comment]
What version of live editor do you have? If you have the v.24.1.1.7 there is no solution and you have to wait for the v.24.1.1.8 to come out for free, or you can just pay for it.

**Comment by kirk024** [comment]
yeah its not working with me too

> With v.24.1.1.8, it doesn't work too

**Comment by CharlesLeclrec123** [comment]
> With v.24.1.1.8, it doesn't work too

I think we need to wait for the new le on 31/7

**Comment by PolishHussar95** [comment]
> What version of live editor do you have? If you have the v.24.1.1.7 there is no solution and you have to wait for the v.24.1.1.8 to come out for free, or you can just pay for it.

You're far off my friend. we support him on patreon and are 2 versions ahead. I have v.24.1.1.9 and its not working. Same issue as OP.

**Comment by xAranaktu** [comment]
Only Live Editor v24.1.1.9 work with TU18.2
