### ISSUE TITLE
Live editor not working?

### ISSUE THREAD

**Issue by PolishHussar95** [xAranaktu/FC-24-Live-Editor#268]
I tried reinstalling the game, updating the EA anti-cheat software, and avoided using the Fake EAC file directly in my FC24 folder. Instead, I relied solely on the LE editor, as it claims to automatically inject the Fake EAC correctly. Despite attempting both methods, the game only launches when the original EA anti-cheat file is present, and I start it without the LE.

When I attempt to launch the game using the LE, nothing happens. It just says "game starting," and Steam indicates that the game is running, but nothing appears on the screen. I waited for 30 minutes with no change. I've experimented with various injection timings ranging from 500ms to 4000ms, but I’m unsure if this makes a difference since it was a fix for the previous update, not the current one. I have the latest LE version, 24.1.1.9 as I support my fellow friend on patreon.

Typically, I’m adept at troubleshooting my files and finding workarounds, as weekly updates or other issues often prevent the game from launching. I always manage to find a solution. My antivirus is turned off, and all relevant files are added to exceptions.

However, I am now at a loss and seeking a possible solution.

Thank you!

**Comment by xAranaktu** [comment]
Only Live Editor v24.1.1.9 work with TU18.2. 
Use 100ms delay. Don't change it.

**Comment by Adib2314** [comment]
free liveditor 1.1.9: https://gamekot.top/soft/fc-24-live-editor-v24-1-1-9

**Comment by chtourou-youssef** [comment]
not work after new update

**Comment by ErickTriton** [comment]
> Only Live Editor v24.1.1.9 work with TU18.2. Use 100ms delay. Don't change it. If it still doesn't work then send log files.

Are we gonna need to wait until the 5th?

**Comment by devilduh** [comment]
> Only Live Editor v24.1.1.9 work with TU18.2. Use 100ms delay. Don't change it. If it still doesn't work then send log files.

i set the delay to 400ms of LE1.1.9, but when i open the game(TU18.2) with LE and FMM, the mod did not work out, all the face mod are not applied(fifer), so is it the problem of the mod or the setting of the LE

**Comment by PolishHussar95** [comment]
> Only Live Editor v24.1.1.9 work with TU18.2. Use 100ms delay. Don't change it. If it still doesn't work then send log files.

Yes i am running TU18.2. But it's still not working. 
if i open LE game thinks its running but its not. And when i close LE i cannot reopen it because it says "Game is open, launch Live editor before the game." when i closed the game and steam says the game is NOT running. So i go in task manager to close EAFC24 and EA background service to launch it. Never had that issue before.

**Comment by PolishHussar95** [comment]
> Only Live Editor v24.1.1.9 work with TU18.2. Use 100ms delay. Don't change it. If it still doesn't work then send log files.

I have fixed it and i know what the issue was. Just for our own education:

Sometimes when you copy the entire folder of the update and paste it into your own folder the Launcher.exe file will not copy properly because you need "admin permission" which is sometimes nonsense because i am logged in as the Administrator. 
So in that case you need to copy the Launcher.exe file to your desktop and delete the old one and move the Launcher.exe from your desktop to whatever file your Live Editor is in.

Thank you for your help!
