### ISSUE TITLE
Live Editor not working on my FC24

### ISSUE THREAD

**Issue by CrypticSweat** [xAranaktu/FC-24-Live-Editor#269]
Hello,
Recently what has been happening is whenever I open Live Editor and then Launch FC24.  It says Game is Starting, then the black screen saying AntiCheat bypassed pops up. But then it goes to the EA app and doesn’t run the game. I also tried running FC24 from Epic Games and not directly from Live Editor, still the same result occurs. However when I run FC24 without Live Editor it works perfectly fine. The current version of my Live Editor is v24.1.1.7 it’s the latest available to everyone. That is my current issue and I would love some help. Thank you.

**Comment by xAranaktu** [comment]
Only Live Editor v24.1.1.9 work with TU18.2
