### ISSUE TITLE
fc 24 wont launch with LE

### ISSUE THREAD

**Issue by hybridpanda12** [xAranaktu/FC-24-Live-Editor#271]
when i use live editor and launch fc 24 through steam the ea prep screen comes up but after that the game nor the splash screen show up but when i look at task manager it says fc 24 is running and stays this way until i end task. also when i try launching without LE the game works as normal.

**Comment by xAranaktu** [comment]
Only [Live Editor v24.1.1.9](https://www.patreon.com/posts/109025352) work with TU18.2
