### ISSUE TITLE
Game doesn't appear on my screen

### ISSUE THREAD

**Issue by shiNokuSki** [xAranaktu/FC-24-Live-Editor#274]
when I launch the game I can see its running on task manager but then I just cant play it bc it just doesnt show up on my screen. Idk if its bc i only have le 24.1.1.8

![image](https://github.com/user-attachments/assets/aa3ee54f-ad81-48ae-93a8-cb6d5b22d703)

**Comment by xAranaktu** [comment]
Only Live Editor v24.1.1.9 work with TU18.2

**Comment by PolishHussar95** [comment]
Also make sure you copied the .exe file to your editor folder properly. I had the same issue when i needed special permission to move the .exe. In that case put it to desktop and from there you can copy and paste it.
Also turn anti-virus off or add editor files to exceptions.
