### ISSUE TITLE
I have this error every time I try to open LE

### ISSUE THREAD

**Issue by Meawtrdytad** [xAranaktu/FC-24-Live-Editor#277]
![Immagine](https://github.com/user-attachments/assets/283fc85b-296d-4904-8d33-a770368cf745)   If I open normally the game does start normally, How can I resolve this error?

**Comment by Meawtrdytad** [comment]
@xAranaktu

**Comment by xAranaktu** [comment]
Repair or reinstall the game.
This should restore original anticheat.

**Comment by Meawtrdytad** [comment]
still has the  same error @xAranaktu  😑😐
