### ISSUE TITLE
ea app problem  fc 24

### ISSUE THREAD

**Issue by ggyuug56ygtg** [xAranaktu/FC-24-Live-Editor#28]
when I open the launcher and click run game 
he try to connect  to ea app and fc 24 does not  work 
![20231129_024807](https://github.com/xAranaktu/FC-24-Live-Editor/assets/152346361/b1f7f24b-a1c1-45fb-b216-528df05f6e8d)

**Comment by xAranaktu** [comment]
As you can read on your screen, you need to run the game in online mode. Without Live Editor.
