### ISSUE TITLE
Live Editor is causing Ea Fc 24 to be ran in the background

### ISSUE THREAD

**Issue by Thegioatedwawdada** [xAranaktu/FC-24-Live-Editor#281]
When i launch Ea Fc 24 with Le It causes Ea fc 24 to be played in the background, I can not access it nor play it, I have tried to run it directly from Ea app but it still is ran in the background. Without le is starts perfectly and runs perfectly . I know ea fc 24 is running when i use it with Le because i can see it in Task Manager. My Dll Injector is set at 4000 ms.

**Comment by emisibal** [comment]
me toooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooo im crazy

**Comment by xAranaktu** [comment]
Only [Live Editor v24.1.1.9](https://www.patreon.com/posts/109025352) work with TU18.2
