### ISSUE TITLE
When I run the game with Live Editor, it doesnt open FC 24, it opens EA

### ISSUE THREAD

**Issue by Alexsyreq** [xAranaktu/FC-24-Live-Editor#282]
So I wanted to try out this mod for the career mode in FC 24. I heard about FC Live Editor and I was curious so I decided to test it out. I checked multiple videos on YouTube, none of them helped my case.
--------
**First of all**, I installed the most recent version of the app which is : **[FC 24 Live Editor v24.1.1.8]**

![Screenshot_1 pngSADASDASDAS png](https://github.com/user-attachments/assets/0b0da947-48a5-4181-becd-9f6193be961b)

Now when I press **"Run Game"** --> 

![image](https://github.com/user-attachments/assets/c0adb324-3150-4a2f-a0ce-c0a4de3762ee)

![image](https://github.com/user-attachments/assets/cd23a22e-c980-4a0a-a7db-a73c3aa75119)

And now I have to wait. But the wait just never stops.
And then, EA opens. Where is Fifa ???? The game is running in background for some reasons 

![image](https://github.com/user-attachments/assets/520df4e4-66d8-4de8-8301-b310bfa04cac)

**Things I did :**
1. I removed **-dataPath FIFAModData** from FC 24 proprieties and FC Live Editor.
2. I tried the previous verions but none of them worked
3. I repaired my FC 24 Files
4. I checked the Live Editor Files and noticed that there is no **config.json** document 
----------
![image](https://github.com/user-attachments/assets/01e3b6eb-17ed-40b7-880d-fe84653a897d)

If someone can help me please

**Comment by xAranaktu** [comment]
Only [Live Editor v24.1.1.9](https://www.patreon.com/posts/109025352) work with TU18.2

**Comment by Royyan5555** [comment]
Sis, I want to quickly play on eafc24, while liveeditor v241.1.9 is paid..please give us a solution 🙏
