### ISSUE TITLE
EAFC not launching via Live Editor

### ISSUE THREAD

**Issue by xTeka** [xAranaktu/FC-24-Live-Editor#284]
Steam and EA app shows that EA FC is launched but i can see it only in task manager

**Comment by blackfaker** [comment]
Also happened to me.
![image](https://github.com/user-attachments/assets/c209230c-83ab-4ed4-a113-183f49130a8b)
stays on injecting, and the task manager shows that it is running 
![image](https://github.com/user-attachments/assets/6b6f9954-ec78-4f02-843b-56a0f3f5c66d)

**Comment by Nathan0715** [comment]
> Also happened to me. ![image](https://private-user-images.githubusercontent.com/177466941/354908604-c209230c-83ab-4ed4-a113-183f49130a8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3ODYwMDUsIm5iZiI6MTcyMjc4NTcwNSwicGF0aCI6Ii8xNzc0NjY5NDEvMzU0OTA4NjA0LWMyMDkyMzBjLTgzYWItNGVkNC1hMTEzLTE4M2Y0OTEzMGE4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxNTM1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjBiMGJmNzhlMWE0YTU0YWU4NDQzZjI4YTc5NDc1ZWFlZWQ2OWNmYzJjNWQ1OThhZTJiMTczOWM4NTdjMmMxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oViFEu1Jnml4tJlEzWM_xHaWFnwvzY_Svja5d05oHmo) stays on injecting, and the task manager shows that it is running ![image](https://private-user-images.githubusercontent.com/177466941/354908674-6b6f9954-ec78-4f02-843b-56a0f3f5c66d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3ODYwMDUsIm5iZiI6MTcyMjc4NTcwNSwicGF0aCI6Ii8xNzc0NjY5NDEvMzU0OTA4Njc0LTZiNmY5OTU0LWVjNzgtNGYwMi04NDNiLTU2YTBmM2Y1YzY2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxNTM1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYThjYjI1N2UwNDkwOWFjOTljYmE2NGQ1ODk3ZjM4NDQyMTkyMDQxOTNjNGY1MGE4ODVhYmI2YzM3OWQ4YTVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.482TzbyX9BBw5hw1mGjoBKYo9MttSLcvPlTMAcknY7U)

I have the same problem.Have you solved?

**Comment by xAranaktu** [comment]
Only [Live Editor v24.1.1.9](https://www.patreon.com/posts/109025352) work with TU18.2
