### ISSUE TITLE
LE injecting error

### ISSUE THREAD

**Issue by Nathan0715** [xAranaktu/FC-24-Live-Editor#285]
I enter the main menu in game and can't find LE menu.
![image](https://github.com/user-attachments/assets/2029ac09-7f4d-4037-bf2e-5fe6899bfe21)

**Comment by Nathan0715** [comment]
![image](https://github.com/user-attachments/assets/d1adeb6f-d199-4763-bce3-c5fa09382528)

**Comment by tookxedo** [comment]
> ![image](https://private-user-images.githubusercontent.com/150140008/354915198-d1adeb6f-d199-4763-bce3-c5fa09382528.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTc3NjgsIm5iZiI6MTcyMjc5NzQ2OCwicGF0aCI6Ii8xNTAxNDAwMDgvMzU0OTE1MTk4LWQxYWRlYjZmLWQxOTktNDc2My1iY2UzLWM1ZmEwOTM4MjUyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxODUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWIwY2FkNDAyYjc5YTkzOWM3MjU0MDNiN2Q1M2EyOWM4ZWM3Mjg1ZTg4ODA0ZjRmMzQyY2FiYjQyZTdiZDMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qlfcJvca6HzeXD-4eQ9694SofflaBOfJZlSEVIaVTPM)

which version of LE did you use?

**Comment by Nathan0715** [comment]
> > ![image](https://private-user-images.githubusercontent.com/150140008/354915198-d1adeb6f-d199-4763-bce3-c5fa09382528.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTc3NjgsIm5iZiI6MTcyMjc5NzQ2OCwicGF0aCI6Ii8xNTAxNDAwMDgvMzU0OTE1MTk4LWQxYWRlYjZmLWQxOTktNDc2My1iY2UzLWM1ZmEwOTM4MjUyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxODUxMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iYWIwY2FkNDAyYjc5YTkzOWM3MjU0MDNiN2Q1M2EyOWM4ZWM3Mjg1ZTg4ODA0ZjRmMzQyY2FiYjQyZTdiZDMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.qlfcJvca6HzeXD-4eQ9694SofflaBOfJZlSEVIaVTPM)
> 
> which version of LE did you use?

![image](https://github.com/user-attachments/assets/19eceb5c-7da4-48a8-9492-ec9188272195)

**Comment by tookxedo** [comment]
@xAranaktu how about this? although he downloaded the latest version of LE...

**Comment by Nathan0715** [comment]
![image](https://github.com/user-attachments/assets/28ea2ff9-b2ee-4f4d-9f87-05d38638e638)
Sometimes I met this error but mostly I enter game while LE was still injecting.

**Comment by xAranaktu** [comment]
Send log files.

**Comment by Nathan0715** [comment]
[log_launcher_05-08-2024.txt](https://github.com/user-attachments/files/16495403/log_launcher_05-08-2024.txt)

**Comment by xAranaktu** [comment]
Looks like your windows user don't have admin rights.

**Comment by eltiger05** [comment]
![error](https://github.com/user-attachments/assets/9ca579c5-1ab1-4b53-a964-f28e21339587)

[log_launcher_05-08-2024.txt](https://github.com/user-attachments/files/16498969/log_launcher_05-08-2024.txt)

[log_05-08-2024.txt](https://github.com/user-attachments/files/16499023/log_05-08-2024.txt)




I launch via Not A Crack for TU18.2

**Comment by Nathan0715** [comment]
> Looks like your windows user don't have admin rights.

![image](https://github.com/user-attachments/assets/397f49c9-e9c0-4760-b04d-659c5b72883b)
looks like I am already admin user.THIS is weird ,as some mods were injected successfully but LE menu hadn't come out when I entered main menu in fc24.
EA's updates have been disappointing. Everything was working fine before Title Update 18.
