### ISSUE TITLE
Live Editor: Starting - Injecting - Nothing happens

### ISSUE THREAD

**Issue by L3x1Hartmann** [xAranaktu/FC-24-Live-Editor#286]
Followed the instructions to install and once i will start the game either manually or via Live Editor nothing happens. Attached 3 Screenshots of Version, Log and task manager.

## Version
![2](https://github.com/user-attachments/assets/bcfc2827-ccda-4e86-84db-09bd890d2659)

## Log file
![1](https://github.com/user-attachments/assets/e3557867-51eb-4ba2-98fb-d165bf9c0d60)

## Task Manager
![3](https://github.com/user-attachments/assets/8bbd16c7-dcc7-455d-949b-2c48fd23746a)

**Comment by ghost** [comment]
It's because you're using the LE version 24.1.1.8 and this version doesn't work with the new TU. Download the newest version instead: https://www.patreon.com/collection/96422?view=expanded
