### ISSUE TITLE
Game starts without my saves with LE

### ISSUE THREAD

**Issue by Mishaelov** [xAranaktu/FC-24-Live-Editor#287]
When I launch the game with LE it asks me to create new settings file.
If I'm trying to create a new settings file it fails, then I just continue without saving but all my CM saving not there.
It also shows the starting intro like I'm playing the game for the first time.

When I launch FC24 without LE it has all my saves.

![image](https://github.com/user-attachments/assets/bbc0e285-32a0-4e9b-bf4c-5eeccf7ead3c)

[log_launcher_05-08-2024.txt](https://github.com/user-attachments/files/16497875/log_launcher_05-08-2024.txt)

LE version:
![image](https://github.com/user-attachments/assets/380aba90-ff7a-4b99-aa7b-eb4d9cc8bac6)

**Comment by xAranaktu** [comment]
Issue with your windows defender.
https://github.com/xAranaktu/FC-24-Live-Editor/issues/45#issuecomment-1869075965

**Comment by Mishaelov** [comment]
Thank you xAranaktu and nullpointer010 for finding the solution.
I had a feeling it's related to windows defender so I excluded LE folder again but of course it didn't help.

Also I wanted to thank you for the hard work for LE & CE for FIFA all these years :)
