### ISSUE TITLE
Not loading in correct save files

### ISSUE THREAD

**Issue by Houndrag** [xAranaktu/FC-24-Live-Editor#289]
Hey,
Whenever I open the game after launching Live editor it opens a completely new save file. How do I sync my original save files to Live editor? I don't want to lose all my progress I made while not using live editor.

**Comment by Houndrag** [comment]
[log_05-08-2024.txt](https://github.com/user-attachments/files/16503246/log_05-08-2024.txt)
[log_launcher_05-08-2024.txt](https://github.com/user-attachments/files/16503248/log_launcher_05-08-2024.txt)

**Comment by Mishaelov** [comment]
I had the same issue today and xAranaktu posted a link to the solution, it worked for me.
It's an issue with Windows Defender
https://github.com/xAranaktu/FC-24-Live-Editor/issues/45#issuecomment-1869075965

**Comment by Houndrag** [comment]
Thank you so much @Mishaelov  It worked, really appreciate man. I like this github thing, im new to it, but is everyone this nice on  here?

**Comment by Mishaelov** [comment]
Yea I believe so, I'm also new here on github, just using xAranaktu's the CT that he is making for FIFA for the last years.
Never posted here until yesterday when I had this issue.
