### ISSUE TITLE
With latest EAFC update my live editor is not starting game.

### ISSUE THREAD

**Issue by efemefetekin** [xAranaktu/FC-24-Live-Editor#29]
Today is 6th December and with todays EAFC 24 update my Live Editor says in Game TU part:  "Your game version is newer than latest known TU by the Live Editor. This tool may not work properly with your game version." Can u help me about this.

**Comment by domatesingabugu** [comment]
exactly

**Comment by efemefetekin** [comment]
Just installed V24.1.1.1 Version and it is not working too. Still same error. Please help!

**Comment by iagopfc** [comment]
Estou na espera da resposta

**Comment by MarinoPosadas** [comment]
The same here. After a while, a Message-Box indicating "1200 attempts without finding the game" shows up.
