### ISSUE TITLE
Launching Issue

### ISSUE THREAD

**Issue by PascalTUDD** [xAranaktu/FC-24-Live-Editor#294]
Yesterday I managed to run Live Editor for the first time, but today I can't figure out why it won't start.
Steps taken to repair:
1) Cleared EA App cache
2) Set DLL injection time to 5000 ms
3) Manually set game location in config.json

I hope @xAranaktu could help me.

[log_07-08-2024.txt](https://github.com/user-attachments/files/16522928/log_07-08-2024.txt)
[log_launcher_07-08-2024.txt](https://github.com/user-attachments/files/16522929/log_launcher_07-08-2024.txt)

**Comment by xAranaktu** [comment]
Change delay to 100ms

**Comment by PascalTUDD** [comment]
Thank you
