### ISSUE TITLE
Live editor stays injecting

### ISSUE THREAD

**Issue by AsierBajoJuan** [xAranaktu/FC-24-Live-Editor#295]
I have tried to set it to 100ms, 5000ms, 6000ms, 7000ms but it stays there all the time, it launches the game but it stays in the background

![image](https://github.com/user-attachments/assets/efa184f3-4336-42c1-91d5-be23a5e1761d)

Logs attached

[log_launcher_08-08-2024.txt](https://github.com/user-attachments/files/16550270/log_launcher_08-08-2024.txt)
[log_08-08-2024.txt](https://github.com/user-attachments/files/16550271/log_08-08-2024.txt)

**Comment by xAranaktu** [comment]
Only [Live Editor v24.1.1.9](https://www.patreon.com/posts/109025352) work with TU18.2
