### ISSUE TITLE
ERROR LOAD PROFILE 

### ISSUE THREAD

**Issue by lucas120e** [xAranaktu/FC-24-Live-Editor#296]
When I start the game it doesn't load
 my profile and when I try to create another profile it gives me an error

![imagen_2024-08-10_095625537](https://github.com/user-attachments/assets/13abd576-a28f-44f7-8dfb-e5ddd6019c25)

**Comment by xAranaktu** [comment]
Issue with your windows defender.
https://github.com/xAranaktu/FC-24-Live-Editor/issues/45#issuecomment-1869075965
