### ISSUE TITLE
Mods Update and when editing some player it's not getting saved or working weirdly

### ISSUE THREAD

**Issue by Ishan96Dev** [xAranaktu/FC-24-Live-Editor#297]
Hey @xAranaktu, I was using `Extended Player and Manager Editor` in Career mode manager and edited the player `Lucas Paquetá` from `West Ham United` Strangely it acted weirdly so I just edited finishing the celebration for him. It's not celebrating that celebration which I selected from him after editing, for example, I saved the celebration for him as `Spanish Dance` but after scoring the goal and when I clicked Button A (From Xbox Controller for Finishing Celebration) he is performing `Floor Spin` Celebration strangely if I am saving for Other Celebrations also he is performing `Floor Spin` Celebration only any idea what's happening Please help and Guide here @xAranaktu, Also the mod looks outdated as there are new celebrations which I see missing in the game. @xAranaktu Please help and guide me here so I can get the quick fix.

**Comment by xAranaktu** [comment]
I don't know solution for your issue.
