### ISSUE TITLE
live editor 1.1.1 not working on the new fifa 24 update

### ISSUE THREAD

**Issue by Strexxxxxx** [xAranaktu/FC-24-Live-Editor#30]
The new uptade of EA FC 24 dropped in december 6, and the live editor 1.1.1 were available in december 7, it will be fixed or we will have to wait until the 1.1.2 be avaiblle for everyone? (sorry for my bad english :P)

**Comment by xAranaktu** [comment]
Only [v24.1.1.2](https://www.patreon.com/posts/fc-24-live-v24-1-94179800) work with Title Update 6. Yes, you need wait for it. It won't be fixed in "1.1.1".

**Comment by Strexxxxxx** [comment]
ok, thanks

Em qui., 7 de dez. de 2023 às 17:58, Paweł ***@***.***>
escreveu:
