### ISSUE TITLE
no game found after 1200 attempts fc 24

### ISSUE THREAD

**Issue by ShadoowTxT** [xAranaktu/FC-24-Live-Editor#32]
how to fix "no game found after 1200 attempts" when running fc 24

**Comment by miguellaraujoo** [comment]
i have the same problem did you fix?

**Comment by ShadoowTxT** [comment]
no yet

**Comment by ShadoowTxT** [comment]
> aku punya masalah yang sama, apakah kamu sudah memperbaikinya?

no

**Comment by Enikbenace** [comment]
I have the same issue, yesterday it worked for me (1st time I used it after becoming a Patreon), now I want to start, I get the same error after a minute or so of "injecting" after pressing "run game". Would like to see this solved please.

**Comment by Enikbenace** [comment]
@miguellaraujoo @ShadoowTxT I solvved it, it seems a restart of my PC and making sure that EA App + Steam (I got the "Steam Version") were running before ever touching the FC LE Launcher did the trick for me. I hope it works for you!

**Comment by ShadoowTxT** [comment]
> @miguellaraujoo 

Is this how it works?

- run steam
- run EA
- open FC LE Launcher
- "run game" in FC LE

*I use the steam version too

**Comment by muwe45** [comment]
Has anyone else found a solution to this error? Ive tried everything else but nothing

**Comment by Enikbenace** [comment]
@muwe45 Did you try my solution? It worked for me.

**Comment by muwe45** [comment]
> @muwe45 Did you try my solution? It worked for me.

yeah, i keep having to repair my ea fc to play it..i am stuck

**Comment by ShadoowTxT** [comment]
> @ShadoowTxTya, ini berhasil untuk saya (saya juga me-restart komputer saya untuk mencobanya setelah kesalahan).

What version of FC LE are you using?

**Comment by ShadoowTxT** [comment]
> i have the same problem did you fix?

Now I have fixed it.

- Open Steam
- Open EA
- Set EA and Steam to offline mode
- Open LE24
- Click play game on Steam
