### ISSUE TITLE
Newest FC 24 live editor won't get me into the game

### ISSUE THREAD

**Issue by o-torske** [xAranaktu/FC-24-Live-Editor#33]
Every time I try to open the game in fc live editor it says "buypassing anticheat", "args(1):", "FC24.exe", and in the end "ok"... But then the window closes, some seconds goes by and then the EA app turns up again without letting me into the game. Then it says "no game found after 1200 attempts".

**Comment by xAranaktu** [comment]
https://github.com/xAranaktu/FC-24-Live-Editor/issues/29#issuecomment-1845832872
