### ISSUE TITLE
menu isnt appearing

### ISSUE THREAD

**Issue by AnimDev-FR** [xAranaktu/FC-24-Live-Editor#35]
![image](https://github.com/xAranaktu/FC-24-Live-Editor/assets/67105787/c7ef9b21-5ecf-4fad-ae12-014152ecf6c9)
i'm subscribed to the patreon and have the latest version available there.

**Comment by xAranaktu** [comment]
It's appearing. You don't see the bar at the top of the game window? You have hidden rest of the windows. Click on "Window" and pick from the list what you need.

**Comment by AnimDev-FR** [comment]
i was talking about the fc 24 menu, with ultimate team, career mode, ect, found out i had to completely hide the windows for it to appear
