### ISSUE TITLE
Profil Save not working 

### ISSUE THREAD

**Issue by Galaxy13011YT** [xAranaktu/FC-24-Live-Editor#38]
I have a problem when I open the game everything launches normally but when I have to choose my profile it tells me to create a new one and without the mods I get my profile back. I have two discs in case it can help.

**Comment by MrwanElashkar** [comment]
Same problem here

**Comment by SheriffLloyd** [comment]
Same here! Same issues with v24.1.1.4.

**Comment by xAranaktu** [comment]
[#45](https://github.com/xAranaktu/FC-24-Live-Editor/issues/45#issuecomment-1869075965)
