### ISSUE TITLE
F24 appears in windows administrator but the game doesn't show up

### ISSUE THREAD

**Issue by MarinoPosadas** [xAranaktu/FC-24-Live-Editor#4]
![2023-10-04_20-26-23](https://github.com/xAranaktu/FC-24-Live-Editor/assets/8512911/a0bdd8bd-b242-452f-a04f-588ed744a6d8)
(and the Laucher folder is excluded from Windows Security)
Thanks

**Comment by xAranaktu** [comment]
Only Live Editor v24.1.0.3 work with Title Update 2.

**Comment by MarinoPosadas** [comment]
Ah! OK. Thanks
