### ISSUE TITLE
Live Editor menu did not show up after launching

### ISSUE THREAD

**Issue by Boennn** [xAranaktu/FC-24-Live-Editor#40]
It says when the game loaded up, the LE menu will show up and we should press F9 to hide it. I never saw the menu popped up. When I press F9, my game will freeze itself, and when I press F9 again, the game will unfreeze. Only the CT works, the LE did not

**Comment by xAranaktu** [comment]
Probably you are using software that's not compatible with LE. 
Check [Blacklist](https://github.com/xAranaktu/FC-24-Live-Editor/wiki/Blacklist). If you are using something from this list then turn it off.
Send live editor log files if doing that won't help.

**Comment by Boennn** [comment]
> Probably you are using software that's not compatible with LE. Check [Blacklist](https://github.com/xAranaktu/FC-24-Live-Editor/wiki/Blacklist). If you are using something from this list then turn it off. Send live editor log files if doing that won't help.

Thank you, Cortex was the problem
