### ISSUE TITLE
Can't save local game files.

### ISSUE THREAD

**Issue by nullpointer010** [xAranaktu/FC-24-Live-Editor#45]
**Description:**
Every time I try to open the game from FC Live Editor or manually from the EA app, I get the message "Failed to Load Settings Files". I also cannot save SquadFile or Career Files.
The editor works correctly and I can edit anything, but I can't save it locally.
When I open the game without the editor, I can do it and the files that I had previously saved appear.

**Problem:**
I think the problem is that it is not able to read or modify the files in C:/Users/User/Documents/FC 24.

**What I have tried to solve it:**

- Open the editor with Administrator Permissions
- Extract the editor in the C: Folder such as C:/FC 24 Editor/ 
- Give permission to all users for the folder C:/Users/User/Documents/FC 24. 
- Manually delete the folder and let the injected game create it 
- Restart everything and try several times.
- Change the game language??

**None of these solutions worked.**

**Comment by nullpointer010** [comment]
I found the solution.
**You need to allow FC24.exe in "Control Folder Access" in Windows Defender.**
It's curious because you don't need to allow it if you run the game without Live Editor.

**Comment by xAranaktu** [comment]
Finally someone found a solution for this. Thanks!
