### ISSUE TITLE
[Question] Script to update new faces for career mode.

### ISSUE THREAD

**Issue by Steveennn** [xAranaktu/FC-24-Live-Editor#52]
Is it possible to use the Live Editor, together with a script that has all the ID's of the players with new faces, to update all these players at once? Or do you need to use the Cheat Engine for this?

**Comment by xAranaktu** [comment]
It's possible with live editor & there is script for that [here](https://github.com/xAranaktu/FC-24-Live-Editor/blob/main/lua/scripts/fix_players_headmodels.lua)
