### ISSUE TITLE
Enum.lua

### ISSUE THREAD

**Issue by AndaleObe** [xAranaktu/FC-24-Live-Editor#53]
I see that in import v2 there is an enum.lua where some are listed. what exactly do these entries mean? There is an entry youth manager there. Does this possibly mean that you could deactivate the youth players at FC24?

**Comment by xAranaktu** [comment]
Uhm... these are career mode managers that are responsible for a lot of stuff. Names should be more or less explanatory.
With "GetManagerObjByTypeId" function you can get the address of an manager instance for further reverse engineering:
```
local addr = GetManagerObjByTypeId(ENUM_FCEGameModesFCECareerModeYouthPlayerManager)
print(string.format("ADDR: 0x%X", addr))
```
I don't know if you can use that to disable generating youth players.

**Comment by AndaleObe** [comment]
> Uhm... these are career mode managers that are responsible for a lot of stuff. Names should be more or less explanatory. With "GetManagerObjByTypeId" function you can get the address of an manager instance for further reverse engineering:
> 
> ```
> local addr = GetManagerObjByTypeId(ENUM_FCEGameModesFCECareerModeYouthPlayerManager)
> print(string.format("ADDR: 0x%X", addr))
> ```
> 
> I don't know if you can use that to disable generating youth players.

yes, they are self-explanatory. Previously, up until FIFA 22, there was an entry in the careersetting.ini youtplayermanager = 1 and with = 0 this could be deactivated. These entries no longer exist since FIFA 23. But I'm pretty sure that youthplayermanager can be deactivated with 0. Unfortunately, I'm a beginner when it comes to looking for pointers.
