### ISSUE TITLE
Version outdated

### ISSUE THREAD

**Issue by woldpus** [xAranaktu/FC-24-Live-Editor#54]
i have the newest version of LE i can get which is 24.1.1.2 but it says the game version is newer than the LE version so i can't run the game at all with LE, how can i fix it?

**Comment by xAranaktu** [comment]
Only [FC 24 Live Editor v24.1.1.3](https://www.patreon.com/posts/fc-24-live-v24-1-96660495) work with EAFC 24 Title Update 7.

**Comment by woldpus** [comment]
when is that coming out free?

**Comment by xAranaktu** [comment]
> when is that coming out free?

Jan 24, 2023 at 11:59 AM CET
