### ISSUE TITLE
FC24 Player Career Transfer

### ISSUE THREAD

**Issue by chan494** [xAranaktu/FC-24-Live-Editor#55]
The option "Is Transfer Listed" in Player Editor is not working in the player's career. I want to be transferred to other teams during the season, but this option keeps returning to 0 (No). And I don't receive teams' requests (in the Notifications section).

@xAranaktu help please!

**Comment by xAranaktu** [comment]
EA removed that option when they added "player agent" thing. It's not possible to put yourself on the transfer list anymore.

**Comment by chan494** [comment]
ok thnkx
