### ISSUE TITLE
fake ea anticheat 

### ISSUE THREAD

**Issue by regge23232** [xAranaktu/FC-24-Live-Editor#56]
when i start ea fc 24 with live editor i get a screen saying fake ea anti cheat launcher is running without the ea anticheat

**Comment by xAranaktu** [comment]
Only [FC 24 Live Editor v24.1.1.3](https://www.patreon.com/posts/fc-24-live-v24-1-96660495) work with EAFC 24 Title Update 7.

**Comment by regge23232** [comment]
im on tu7 still happens
