### ISSUE TITLE
import wrong miniface format, now live editor crashes when i edit this player

### ISSUE THREAD

**Issue by MarkB82** [xAranaktu/FC-24-Live-Editor#58]
Hi,

i imported a wrong miniface for Raul (i forget to delete the background in the dds file), the live editor crash asap.

i clicked the LiveEditorClearRegistry.reg, but the crash for Raul trigger immediately after click him, i don't come to the part to choose another miniface anymore.

What can i do? 

Thanks in advance

**Comment by xAranaktu** [comment]
You have two options:
1. Disable loading images in live editor settings, then open Raul in player editor and delete his miniface
2. Go to `C:\FC 24 Live Editor\mods\root\Legacy\data\ui\imgAssets\heads` and delete invalid image
