### ISSUE TITLE
Game crashes a few seconds after launch

### ISSUE THREAD

**Issue by zerokeiara** [xAranaktu/FC-24-Live-Editor#59]
When I click run game, it starts the game as normal, but then it crashes after a few seconds.
Here's the log file.
[log_launcher_24-01-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14040849/log_launcher_24-01-2024.txt)

[log_24-01-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14040847/log_24-01-2024.txt)

**Comment by xAranaktu** [comment]
Turn off Razer Cortex
