### ISSUE TITLE
game crashes when editing certain feature of players

### ISSUE THREAD

**Issue by ViviantGG** [xAranaktu/FC-24-Live-Editor#62]
Hey. I am having a problem when trying to edit specifically youth players. Some of the players I want to edit their skin type, ethnicity, hair color a few other settings. Once I click on what I want to change it to the game crashes. Sometimes when it tells me my graphics driver needs updating but it still crashes when my graphic drivers are up to date.

**Comment by xAranaktu** [comment]
Disable loading images in live editor settings.
