### ISSUE TITLE
start game problem

### ISSUE THREAD

**Issue by jeniffer88** [xAranaktu/FC-24-Live-Editor#64]
Hello... I really love this mod and use it all the time, thank you so much for this <3

I never had this problem in the past, but when I downloaded the last update and entered the game, it says this

![Untitled](https://github.com/xAranaktu/FC-24-Live-Editor/assets/157715608/4b7411da-196e-4c80-bb03-d36e3366bb72)

When I start the game without the program it works fine, can you help me?

Thank you very much ♥

**Comment by xAranaktu** [comment]
send log files

**Comment by jeniffer88** [comment]
[log_26-01-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14062095/log_26-01-2024.txt)
[log_launcher_26-01-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14062096/log_launcher_26-01-2024.txt)

**Comment by xAranaktu** [comment]
Turn off RivaTuner

**Comment by jeniffer88** [comment]
Well, I'll try .......
Thanks for your attention ♥
