### ISSUE TITLE
Player Edits Not Saving

### ISSUE THREAD

**Issue by Owieener** [xAranaktu/FC-24-Live-Editor#66]
1. Since the release of the new version for TU7 I've not been able to properly save changes on players (real or create-a-player). The changes save initially, but as soon as I go into kickoff mode all of the changes get removed. 

2. The join team year function hasn't been working for a while, and always resets to year 1900 after changes are saved.

3. The game crashes when deleting a generated miniface, has been doing this since the start of FC24.

Any updates or help is much appreciated!

**Comment by xAranaktu** [comment]
1 & 2 - You are talking about the "Extended Player & Manager Editor" mod, or about the "player editor" feature that is a part of the live editor?

3 - Disable loading images in live editor settings, or just manually delete the files from "C:\FC 24 Live Editor\mods\root\Legacy\data\ui\imgAssets\heads"

**Comment by Owieener** [comment]
I’m talking about the “player editor” feature that is part of the live editor. Changes such as alternate positions, work rates, play styles, potential, and the defensive awareness attribute reset once going in to kickoff mode.

**Comment by xAranaktu** [comment]
The tool is made for career mode. If something isn't working in kickoff then it isn't working. I don't care tbh.

**Comment by Owieener** [comment]
Bit rude, but alright then
