### ISSUE TITLE
Game loads but closes instantly

### ISSUE THREAD

**Issue by McFelipardo** [xAranaktu/FC-24-Live-Editor#67]
Ive recently downloaded LE and it worked fine for the first time, but now when i launch the game in LE it closes automatically despite passing the Anti Cheat. 

Ive tried running the game as administrator or changing where i open the game and the issue remains the same.
Please help.

**Comment by xAranaktu** [comment]
send log files.

**Comment by McFelipardo** [comment]
nvm i accidently messed with file placement and it fixed it self
