### ISSUE TITLE
Crash when load manager save career mode

### ISSUE THREAD

**Issue by anhduytran98** [xAranaktu/FC-24-Live-Editor#68]
Dear xAranaktu,
Can you check my crash report and log launcher files cause i have crashed when I use cheat editor to edit and create a clone. I have restart the game and load career mode but it crash again, How can I fix it? Thank you very much 
[CrashReport_27012024192901307.json](https://github.com/xAranaktu/FC-24-Live-Editor/files/14072301/CrashReport_27012024192901307.json)
[CrashReport_27012024192521871.json](https://github.com/xAranaktu/FC-24-Live-Editor/files/14072303/CrashReport_27012024192521871.json)
[CrashReport_27012024181411207.json](https://github.com/xAranaktu/FC-24-Live-Editor/files/14072305/CrashReport_27012024181411207.json)

[log_launcher_27-01-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14072302/log_launcher_27-01-2024.txt)

**Comment by xAranaktu** [comment]
You have corrupted player data while editing him/cloning.
