### ISSUE TITLE
No mods were found inside the archive file

### ISSUE THREAD

**Issue by Mattihg** [xAranaktu/FC-24-Live-Editor#69]
When i try to import the live editor mod into mod manager it says No mods were found inside the archive file. i´ve tried to find videos regarding this issue but couldnt find anything useful. i am new to modding, only just began this year so if anyone could help me out i would be grateful.

**Comment by xAranaktu** [comment]
If you want to use modified files from live editor mod in FET you need to import these files on by one in FET.
