### ISSUE TITLE
FC 24 IDs Google Docs

### ISSUE THREAD

**Issue by cordobes90** [xAranaktu/FC-24-Live-Editor#7]
Hello, first of all, great work, I wanted to know when you will put the FC24 IDs in Google docs like previous years.

https://docs.google.com/spreadsheets/d/1cDpeenm3RYBi5VPvcvdFChD7kwKB126TTsr4Zf6u_7A/edit#gid=0

**Comment by Oliver-Turp** [comment]
It already has: https://docs.google.com/spreadsheets/d/1pN0A1KoPsTS1Bc6RMBXz9NDP-VkvkDpOnw1QQaoW_DE/edit#gid=0

Should join the discord: https://discord.gg/va9EtdB

Lots of info there
