### ISSUE TITLE
Launcher will "load" game but not actually pop up to be playable. Only after new Game upodate

### ISSUE THREAD

**Issue by jfxrbes** [xAranaktu/FC-24-Live-Editor#71]

**Comment by jfxrbes** [comment]
![image](https://github.com/xAranaktu/FC-24-Live-Editor/assets/126541550/df0602b9-2d44-4703-b45c-7ec8d286b361)

**Comment by iamfc24player** [comment]
its gonna take at least a day for them to make the tu8 update 
also i have a problem in tu7 when i sim calendar with LE it takes 10 years (tried making messi 20 with 09 stats but it took me an entire hour to sim a season can u help me with this)
