### ISSUE TITLE
game doesnt start

### ISSUE THREAD

**Issue by linus005** [xAranaktu/FC-24-Live-Editor#73]
After launching LE, the game doesnt start, no matter i press "run game" or do it manually in steam.

**Comment by xAranaktu** [comment]
Live Editor doesn't work with Title Update 8. Wait for LE v24.1.1.4.

**Comment by linus005** [comment]
> Live Editor doesn't work with Title Update 8. Wait for LE v24.1.1.4.
thanks a lot!

**Comment by darkraids** [comment]
do you know when this will be updated?

**Comment by xAranaktu** [comment]
> do you know when this will be updated?

[Release Schedule](https://bit.ly/FC-24-Release-Schedule)

**Comment by darkraids** [comment]
ok thank you :)
