### ISSUE TITLE
tu8 release

### ISSUE THREAD

**Issue by iamfc24player** [xAranaktu/FC-24-Live-Editor#75]
when will it releas

**Comment by xAranaktu** [comment]
No ETA. Will be released when I'll find a way to bypass new anticheat protection.

**Comment by xAranaktu** [comment]
It's out for Patrons already.
[Release Schedule](https://docs.google.com/spreadsheets/d/1QQzz37XEH1VCN4pJ0G2dwCfg4jLbYehLcVP-h3qIjr8/edit#gid=1821816083)

**Comment by iamfc24player** [comment]
> It's out for Patrons already. [Release Schedule](https://docs.google.com/spreadsheets/d/1QQzz37XEH1VCN4pJ0G2dwCfg4jLbYehLcVP-h3qIjr8/edit#gid=1821816083)

alr thanks
