### ISSUE TITLE
Trojan warning

### ISSUE THREAD

**Issue by Mattihg** [xAranaktu/FC-24-Live-Editor#76]
When i open the live editor, my computer warns me that the live editor file is infected with a trojan virus. i was wondering what is triggering this issue, as it has never happened for me before using the live editor.

**Comment by xAranaktu** [comment]
False positive. I don't know why your antivirus detected the problem just now. Same thing happens for various users with various versions in the past. It's not like it's something new. You can check messages on discord or perhaps older issues on github, I guarantee you will find exact same posts as yours create 1 month ago, 3 months ago and even 1 year ago.
