### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by iamfc24player** [xAranaktu/FC-24-Live-Editor#80]
add something like "change player to older fifa" (fifa 09 10 or 11+ because not all stats were made in 10 or 11 idk i made messi but only 2 stats were missing so)

**Comment by Alikocakk** [comment]
You cannot be serious do you know how much work it's gonna took take haha

**Comment by iamfc24player** [comment]
> You cannot be serious do you know how much work it's gonna took take haha

yea i didnt realise that for the thousands of cards in fc
