### ISSUE TITLE
Can you help

### ISSUE THREAD

**Issue by snenes** [xAranaktu/FC-24-Live-Editor#81]
Hello I am writing from Turkey I wanted to get silver membership on patreon but when I enter my card information, it gives an error even though I tried many times. I guess there is no payment with Turkish lira on Patreon. I also tried with dollars and euros but it didn't work.

What can I do ???

**Comment by xAranaktu** [comment]
Patreon is the only way to pay for the product that I accept. 
I don't know why your payment doesn't go through. You need to contract with patreon support.
I can't help with problems with payment, sorry.
