### ISSUE TITLE
v24.1.1.4  Not Working

### ISSUE THREAD

**Issue by furkannkarol** [xAranaktu/FC-24-Live-Editor#82]
Doesn't start the game.
I'm going back to the EA app

**Comment by xAranaktu** [comment]
run the game without mods

**Comment by furkannkarol** [comment]
I don't use mods

**Comment by furkannkarol** [comment]
I don't use mods

**Comment by xAranaktu** [comment]
send log files then

**Comment by furkannkarol** [comment]
[log_03-02-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14152732/log_03-02-2024.txt)
[log_launcher_03-02-2024.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14152733/log_launcher_03-02-2024.txt)

**Comment by furkannkarol** [comment]
today these

**Comment by xAranaktu** [comment]
Seems like live editor doesn't work with trial game version.

**Comment by furkannkarol** [comment]
I don't understand

**Comment by furkannkarol** [comment]
what should I do?

**Comment by xAranaktu** [comment]
In log file is see that the name of game process is `FC24_Trial.exe` which indicates that you have ea play basic plan which allows you to play the game for 10h only. Trial is probably different that full version and that's why live editor doesn't work with it.
Nothing you can do about that.
Try live editor again if you ever decide to buy full game version

**Comment by furkannkarol** [comment]
this game is already full version
I don't play demo

**Comment by furkannkarol** [comment]
Is there a way to launch it via Steam launcher?

**Comment by furkannkarol** [comment]
My friend, live editor worked when I ran it via Steam.

**Comment by furkannkarol** [comment]
Worked :))))))

**Comment by xAranaktu** [comment]
> this game is already full version I don't play demo

So I assume you have enabled "Is Trial" in live editor settings and that's why the live editor launcher starts trial game process when you click on "Run Game" button. Disabling "Is Trial" option should fix the problem, but probably launching the game via steam is still better

**Comment by furkannkarol** [comment]
I DON'T KNOW WHERE THIS OPTION IS, I WILL TRY IT

**Comment by raizor19** [comment]
v24.1.1.5 data?
