### ISSUE TITLE
EA FC 24 Live Editor Deleting Personal Saves

### ISSUE THREAD

**Issue by ScuderiaNL24** [xAranaktu/FC-24-Live-Editor#84]
If i use the EA FC 24 Live Editor it deletes all my Personal Saves but if i start the game normally its back
Can anyone help me pls.

**Comment by xAranaktu** [comment]
[You need to allow FC24.exe in "Control Folder Access" in Windows Defender](https://github.com/xAranaktu/FC-24-Live-Editor/issues/45)
