### ISSUE TITLE
Acceleration types and playstyles limitations ? 

### ISSUE THREAD

**Issue by AmrKhan25** [xAranaktu/FC-24-Live-Editor#93]
Anyway to change acceleration type ? It defaults to controlled with created players and even if I added quick step+ the player feels slow compared to an explosive type acceleration like Mbappe

Also does adding playstyles have limitations ? Like the amount to add or some make others don't work ?
For example if I added all playstyles+ to a player some just don't work or are they working but their indicators are just bugged out and don't show up ? clarification is needed and thanks in advance.

**Comment by xAranaktu** [comment]
1. To change accelerate type you need to change player attributes. There is no other way. Check[this](https://www.ea.com/games/ea-sports-fc/pitch-notes/news/fc-24-gameplay-deepdive)

2. Well, you have answered your own question. If you assigned all playstyles and some of them doesn't work then it means there is a limit. I don't know how many playstyles+ you can assign to the player.
