### ISSUE TITLE
Fake EA Anticheat Launcher 

### ISSUE THREAD

**Issue by jxhnyb99** [xAranaktu/FC-24-Live-Editor#94]
I have this problem with the the Liveeditor Launcher.
I click "Run Game" an this window opens. I don't know what to do.

![Screenshot 2024-02-11 001454](https://github.com/xAranaktu/FC-24-Live-Editor/assets/159666973/f5969515-276a-4fab-b706-981f42da02a5)
![Screenshot 2024-02-11 001542](https://github.com/xAranaktu/FC-24-Live-Editor/assets/159666973/1e3217ef-a20c-42e0-bccf-6bec43d9690b)

**Comment by xAranaktu** [comment]
Only Live Editor v24.1.1.4 work with Title Update 8.
