### ISSUE TITLE
Profile Save Not Working With V24.1.1.4

### ISSUE THREAD

**Issue by SheriffLloyd** [xAranaktu/FC-24-Live-Editor#95]
I've an issue with last update v24.1.1.4. when I open the game everything launches normally but when I tryna open the game with live editor it tells me to create a new profile and without live editor there's no problem. I had no problem with v24.1.1.3. Could someone help ?

**Comment by xAranaktu** [comment]
[#45](https://github.com/xAranaktu/FC-24-Live-Editor/issues/45#issuecomment-1869075965)
