### ISSUE TITLE
FC 24 crashing  after splash screen

### ISSUE THREAD

**Issue by TheaFa** [xAranaktu/FC-24-Live-Editor#96]
So I installed FC 24 and it is crashing after showing splash screen. It shows the error: NULL_POINTER_READ_c0000005_FC24.exe!Unknown. I think it is due to the anticheat(everyone is complaining btw)

I installed the live editor and it is still crashing and it's the latest download... Pls any help
The crash file was reading : NULL_POINTER_READ_c0000005_FC24.exe!Unknow
[crash file.txt](https://github.com/xAranaktu/FC-24-Live-Editor/files/14233913/crash.file.txt)

This topic has been on ea forum and reddit...no fix.. we are trying to use ur fake Anticheat to bypass it... Is it possible for it to work ... Pls answer @xAranaktu
Thanks in advance

**Comment by xAranaktu** [comment]
`crash_file.txt` you sent is from 20th January and was captured on older game version. Send at least latest one captured on Title Update 8.
But imo. live editor will not help with that if you tried it. Probably your issue isn't related to the anticheat.

**Comment by TheaFa** [comment]
> `crash_file.txt` you sent is from 20th January and was captured on older game version. Send at least latest one captured on Title Update 8. But imo. live editor will not help with that if you tried it. Probably your issue isn't related to the anticheat.

Can't the fake Anticheat bypass the real one or something

**Comment by TheaFa** [comment]
> `crash_file.txt` you sent is from 20th January and was captured on older game version. Send at least latest one captured on Title Update 8. But imo. live editor will not help with that if you tried it. Probably your issue isn't related to the anticheat.

By chance do u know what that error means...I can't figure it out

**Comment by xAranaktu** [comment]
```
Can't the fake Anticheat bypass the real one or something
```
When you run the game with the live editor the original anticheat isn't loaded at all. 
"fake Anticheat bypass" is a minor thing in this whole process of bypassing the EAAC. Live Editor is the actual bypass of EAAC.

```
By chance do u know what that error means...I can't figure it out
```
Google -> `null pointer read`

**Comment by MateiSlavu** [comment]
I still have the same problem, it won't open it stays blocked on the splash scrren
