### ISSUE TITLE
FC 24 crashing after playing manager mode

### ISSUE THREAD

**Issue by anhduytran98** [xAranaktu/FC-24-Live-Editor#97]
Hi, first thank you for your update on the new title update and I appreciate your work. I will continue to subscribe to your project on Patreon.

I have a question, every time I play manager mode, after 2,3 seasons, the game crash. On LE Editor logs show this error, do you know how to fix? I only use creat player function inside the game only. So do you know how to fix the crash. Thank you very much
![image](https://github.com/xAranaktu/FC-24-Live-Editor/assets/74843979/cd2639cc-ba1c-4c73-8bbe-36f705bf4480)

I also send you the crash log here to check as well. Thank you
[CrashReport_11022024192444667.json](https://github.com/xAranaktu/FC-24-Live-Editor/files/14239410/CrashReport_11022024192444667.json)
[CrashReport_11022024193541546.json](https://github.com/xAranaktu/FC-24-Live-Editor/files/14239411/CrashReport_11022024193541546.json)
[
[CrashReport_12022024221319167.json](https://github.com/xAranaktu/FC-24-Live-Editor/files/14239953/CrashReport_12022024221319167.json)
](url)

**Comment by xAranaktu** [comment]
The error you see in live editor log isn't the reason of your game crashes.

I've checked the `CrashReport_11022024192444667.json` file and to me it looks like there is possible problem with player with id `280574`. I don't know what caused this problem. It can be caused by the mods you use, squadfile you used to start your career or simply by the things you have edited.

**Comment by anhduytran98** [comment]
> The error you see in live editor log isn't the reason of your game crashes.
> 
> I've checked the `CrashReport_11022024192444667.json` file and to me it looks like there is possible problem with player with id `280574`. I don't know what caused this problem. It can be caused by the mods you use, squadfile you used to start your career or simply by the things you have edited.

First thank you very much for your support. Is there any case that related to the graphic driver or elses, cause I just delete the game and all the save file and reinstall it and it still crash

**Comment by xAranaktu** [comment]
I don't know if it's related to your graphics driver.
CrashReport is json file, you can open it even in notepad. I don't think the info there will help you at all.
