### ISSUE TITLE
Detected Virus from an Attacker

### ISSUE THREAD

**Issue by Beehive804** [xAranaktu/FC-24-Live-Editor#98]
![Screenshot 2024-02-13 170254](https://github.com/xAranaktu/FC-24-Live-Editor/assets/60082247/8313df2d-70a2-4cf7-a210-3e6a08b0a7b7)

I was wondering what I should do beause of this. Is there a percaution I missed? This is the second time this happned to me the first time was 24.1.09. I havent seen anyone else with a problem like this. I always play offline so is there a reason to why this happens. Should I redownload v24.1.1.4?

**Comment by xAranaktu** [comment]
Add folder with live editor to exceptions in your antivirus.
